import { t } from "@/lib/t";

/**
 * The plumbing every printable document in the preview shares.
 *
 * The preview can now print four different documents off the same previewed
 * draw — the run sheet, the court grid, the draw, and the court-time report.
 * They differ in what they say; they must NOT differ in how they say it, so
 * the header band, the escaping rule, the crest rule, the print handshake and
 * the download are written once here.
 */

export function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * A team crest for a printed document, or NOTHING when the team has no badge.
 *
 * These pages are generated HTML, so `components/ui/TeamCrest` (and its
 * on-error fallback to initials) cannot run here. A printed sheet has no way
 * to recover from a missing image either: it would carry the browser's broken
 * -image icon onto the paper. So the rule is absolute — no crest, no tag.
 *
 * Styles are inline because the document is written into a fresh tab and must
 * survive being saved or re-opened on its own.
 */
export function crestImg(url: string, size = 14): string {
  if (!url) return "";
  return (
    `<img src="${esc(url)}" alt="" width="${size}" height="${size}" ` +
    `style="border-radius:50%;object-fit:cover;vertical-align:middle;` +
    `margin-right:4px;border:1px solid #e5e7eb;background:#fff">`
  );
}

/** The rules every document uses: the brand band, the meta lines, the page. */
export function baseCss(orientation: "landscape" | "portrait" = "landscape"): string {
  return `
  * { box-sizing: border-box; margin: 0; }
  body { font: 9.5px/1.35 Inter, system-ui, -apple-system, "Segoe UI", sans-serif; color: #111827; padding: 24px; background: #fff;
         -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .band-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; border-bottom: 3px solid #6840dd; padding-bottom: 8px; }
  h1 { font-size: 16px; font-weight: 600; letter-spacing: -0.01em; }
  .sub { color: #6b7280; font-size: 10px; margin-top: 2px; }
  .brand { color: #6840dd; font-size: 10px; font-weight: 600; white-space: nowrap; }
  .meta { color: #6b7280; font-size: 9px; margin-top: 6px; }
  .filters { color: #6840dd; font-size: 9px; margin-top: 2px; }
  .draft { color: #b45309; font-size: 9px; margin-top: 2px; font-weight: 600; }
  .foot { margin-top: 12px; color: #9ca3af; font-size: 8px; }
  thead { display: table-header-group; }
  tr { break-inside: avoid; }
  @page { size: A4 ${orientation}; margin: 10mm; }
  @media print { body { padding: 0; } }`;
}

/** "20 August 2026, 04:12 PM" in the reader's own locale. */
export function stampNow(): string {
  return new Date().toLocaleString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/** The band every document opens with: what it is, when, and how filtered. */
export function docHeader({
  title,
  subtitle,
  scope,
  filterSummary,
  note,
}: {
  title: string;
  subtitle: string;
  /** "108 matches", "12 court days" — what this document counts. */
  scope: string;
  filterSummary?: string;
  /** The trial-run warning, already worded by the caller. */
  note?: string;
}): string {
  return `<div class="band-top">
    <div>
      <h1>${esc(title)}</h1>
      <p class="sub">${esc(subtitle)}</p>
    </div>
    <div class="brand">fixture.doxaed.com</div>
  </div>
  <p class="meta">${esc(t("Exported"))} ${esc(stampNow())} · ${esc(scope)}</p>
  ${filterSummary ? `<p class="filters">${esc(t("Filters applied"))}: ${esc(filterSummary)}</p>` : ""}
  ${note ? `<p class="draft">${esc(note)}</p>` : ""}`;
}

export function docFooter(): string {
  return `<p class="foot">${esc(t("Generated by Fixture"))} · fixture.doxaed.com</p>`;
}

/** `fixture-draw-all-competitions-2026-08-20` — one naming rule for all. */
export function fileStem(kind: string, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `fixture-${kind}-${slug || "schedule"}-${new Date().toISOString().slice(0, 10)}`;
}

/** Hand the browser a file to save. BOM so Excel reads names as UTF-8. */
export function downloadCsv(csv: string, filename: string): void {
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function csvCell(v: string): string {
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

/** Rows of already-resolved text as one CSV body. */
export function csvOf(
  head: readonly string[],
  rows: readonly (readonly string[])[],
): string {
  return [
    head.map(csvCell).join(","),
    ...rows.map((r) => r.map(csvCell).join(",")),
  ].join("\n");
}

/**
 * Raise the print dialog once the crests have actually arrived.
 *
 * A bare `setTimeout(print, 250)` is a guess, not a handshake. Every crest is
 * a signed URL the NEW tab has to fetch for itself, and a sheet can carry
 * hundreds of them; print while they are still in flight and the badges come
 * out of the printer as blank squares. So we wait on each image's own
 * load/error and only then print.
 *
 * The 1500ms ceiling is the other half of the deal: one dead crest URL must
 * never hold the dialog hostage, because the schedule on the page is the part
 * the reader actually came for. (Same handshake as
 * `features/tournaments/tabs/institutionExport.ts` — keep the two in step.)
 */
export function printWhenImagesReady(w: Window): void {
  let printed = false;
  const doPrint = (): void => {
    if (printed) return;
    printed = true;
    w.print();
  };
  // Guarded: a document stub with no query API is still a printable window.
  const all = w.document.querySelectorAll
    ? Array.from(w.document.querySelectorAll("img"))
    : [];
  const pending = all.filter((img) => !img.complete);
  if (!pending.length) {
    setTimeout(doPrint, 250);
    return;
  }
  let left = pending.length;
  const settle = (): void => {
    left -= 1;
    // A beat after the last one so the layout it changed has painted.
    if (left <= 0) setTimeout(doPrint, 50);
  };
  for (const img of pending) {
    img.addEventListener("load", settle);
    img.addEventListener("error", settle);
  }
  setTimeout(doPrint, 1500);
}

/**
 * Open a generated document in a new tab and raise the print dialog —
 * "Save as PDF" there gives the shareable file. Everything is inlined, so the
 * document needs no network and no PDF dependency.
 */
export function openPrintable(html: string): void {
  // NO "noopener": with it window.open returns null, leaving a blank tab we
  // can never write into. The document is our own, same-origin.
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  printWhenImagesReady(w);
}
