# Generated by Django 5.1.15 on 2026-07-04 17:55

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('prefs', models.JSONField(blank=True, default=dict)),
                ('digest', models.BooleanField(default=False)),
                ('digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
    ]
