# Generated by Django 5.1.15 on 2026-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
