# Generated by Django 5.1.15 on 2026-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_venue_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
