# Generated by Django 5.1.15 on 2026-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_venue_unavailable_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='sports',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
