# Generated by Django 5.1.15 on 2026-06-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_venue_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='breaks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
