# Generated by Django 5.1.15 on 2026-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0006_court"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="competitions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
