# Generated by Django 5.1.15 on 2026-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_court_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
    ]
