# Generated by Django 5.1.15 on 2026-08-21 08:56

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0008_court_exclusive'),
        ('organizations', '0006_organization_school_profile'),
        ('tournaments', '0012_tournament_roster_mode_alter_tournament_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('generated', 'Fixture generated'), ('scheduled', 'Schedule run'), ('manual', 'Saved by hand'), ('restored', 'Restored from an earlier fixture')], default='manual', max_length=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_snapshots', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_snapshots', to='organizations.organization')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_snapshots', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'fixtures_fixturesnapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', '-created_at'], name='fixsnap_trn_created_idx')],
            },
        ),
    ]
