# Generated by Django 5.1.15 on 2026-06-05 07:47

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0003_remove_admininvitation_unique_pending_invite_per_email_per_org_and_more",
        ),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("dob_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teams_person",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=40)),
                ("school", models.CharField(blank=True, max_length=200)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("pool", models.CharField(blank=True, max_length=80)),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending approval"),
                            ("registered", "Registered"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("disqualified", "Disqualified"),
                        ],
                        db_index=True,
                        default="registered",
                        max_length=24,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="organizations.organization",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "teams_team",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jersey_no", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, max_length=16)),
                ("captain", models.BooleanField(default=False)),
                ("is_goalkeeper", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="teams.person",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "teams_player",
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["full_name"], name="person_full_name_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["tournament", "status"], name="team_trn_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("tournament", "slug"), name="unique_team_slug_per_tournament"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tournament", "name"),
                name="unique_team_name_per_tournament",
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["team"], name="player_team_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["person"], name="player_person_idx"),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("jersey_no__isnull", False)
                ),
                fields=("team", "jersey_no"),
                name="unique_jersey_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tournament", "person"),
                name="unique_person_per_tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                condition=models.Q(("captain", True), ("deleted_at__isnull", True)),
                fields=("team",),
                name="unique_captain_per_team",
            ),
        ),
    ]
