# Generated by Django 5.1.15 on 2026-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_registrationlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationlink",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationlink",
            name="max_submissions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationlink",
            name="submission_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
