# Generated by Django 5.1.15 on 2026-06-08 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_admininvitation_status'),
        ('teams', '0003_registrationlink_expires_at_and_more'),
        ('tournaments', '0004_backfill_tournament_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('club', 'Club'), ('academy', 'Academy'), ('other', 'Other')], default='school', max_length=16)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('registered', 'Registered'), ('withdrawn', 'Withdrawn'), ('rejected', 'Rejected')], db_index=True, default='registered', max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source_response_id', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='organizations.organization')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'teams_institution',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.institution'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['tournament', 'status'], name='inst_trn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['organization'], name='inst_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('tournament', 'slug'), name='unique_institution_slug_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tournament', 'name'), name='unique_institution_name_per_tournament'),
        ),
    ]
