# Generated by Django 5.1.15 on 2026-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_backfill_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leaf_key',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
