# Generated by Django 5.1.15 on 2026-06-10 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_admininvitation_status'),
        ('teams', '0006_team_leaf_key_team_sport'),
        ('tournaments', '0006_tournament_scheduling_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_person_per_tournament',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('team', 'person'), name='unique_person_per_team'),
        ),
    ]
