# Generated by Django 5.1.15 on 2026-06-10 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_admininvitation_status'),
        ('teams', '0007_remove_player_unique_person_per_tournament_and_more'),
        ('tournaments', '0006_tournament_scheduling_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_name_per_tournament',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tournament', 'leaf_key', 'name'), name='unique_team_name_per_competition'),
        ),
    ]
