# Generated by Django 5.1.15 on 2026-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_unique_team_name_per_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='team_code_hash',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institution',
            name='team_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
