# Generated by Django 5.1.15 on 2026-07-04 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_branding_organization_is_listed_and_more'),
        ('teams', '0009_institution_team_code_hash_and_more'),
        ('tournaments', '0009_backfill_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('club', 'Club'), ('academy', 'Academy'), ('other', 'Other')], default='school', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='teams.schoolprofile')),
            ],
            options={
                'db_table': 'teams_school_profile',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='school_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='teams.schoolprofile'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='organizations.organization')),
            ],
            options={
                'db_table': 'teams_season',
            },
        ),
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('house', 'House'), ('class', 'Class'), ('form', 'Form'), ('department', 'Department')], default='house', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('colour', models.CharField(blank=True, max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to='organizations.organization')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teams.season')),
            ],
            options={
                'db_table': 'teams_team_group',
            },
        ),
        migrations.CreateModel(
            name='HousePointEntry',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('result', 'Result'), ('judged', 'Judged')], default='judged', max_length=16)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_points_awarded', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_point_entries', to='organizations.organization')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_point_entries', to='tournaments.tournament')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to='teams.season')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to='teams.teamgroup')),
            ],
            options={
                'db_table': 'teams_house_point_entry',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.teamgroup'),
        ),
        migrations.AddIndex(
            model_name='schoolprofile',
            index=models.Index(fields=['normalized_name', 'region'], name='school_profile_ident_idx'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='unique_season_label_per_org'),
        ),
        migrations.AddConstraint(
            model_name='teamgroup',
            constraint=models.UniqueConstraint(fields=('season', 'name'), name='unique_group_name_per_season'),
        ),
        migrations.AddIndex(
            model_name='housepointentry',
            index=models.Index(fields=['season', 'group'], name='house_points_season_idx'),
        ),
    ]
