# Generated by Django 5.1.15 on 2026-08-16 13:32

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organization_school_profile"),
        ("teams", "0010_schoolprofile_institution_school_profile_season_and_more"),
        ("tournaments", "0011_tournament_group_kind_tournament_scope_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "House manager")],
                        default="manager",
                        max_length=16,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "teams_team_group_membership",
            },
        ),
        migrations.CreateModel(
            name="TournamentHouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "teams_tournament_house",
            },
        ),
        migrations.RemoveConstraint(
            model_name="teamgroup",
            name="unique_group_name_per_season",
        ),
        migrations.AddField(
            model_name="teamgroup",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="teamgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("season", "name"),
                name="unique_group_name_per_season",
            ),
        ),
        migrations.AddField(
            model_name="teamgroupmembership",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="house_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamgroupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="teams.teamgroup",
            ),
        ),
        migrations.AddField(
            model_name="teamgroupmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_group_memberships",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="teamgroupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamenthouse",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_entries",
                to="teams.teamgroup",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthouse",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_houses",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="tournamenthouse",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddIndex(
            model_name="teamgroupmembership",
            index=models.Index(
                fields=["user", "revoked_at"], name="house_member_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamgroupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("group", "user"),
                name="unique_active_house_member",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamenthouse",
            index=models.Index(fields=["tournament"], name="tournament_house_trn_idx"),
        ),
        migrations.AddConstraint(
            model_name="tournamenthouse",
            constraint=models.UniqueConstraint(
                fields=("tournament", "group"), name="unique_house_per_tournament"
            ),
        ),
    ]
