# Generated by Django 5.1.15 on 2026-08-16 15:14

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organization_school_profile"),
        ("teams", "0011_teamgroupmembership_tournamenthouse_and_more"),
        ("tournaments", "0012_tournament_roster_mode_alter_tournament_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RosterMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher in charge"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=16,
                    ),
                ),
                ("class_section", models.CharField(blank=True, max_length=32)),
                ("roll_no", models.CharField(blank=True, max_length=32)),
                ("gender", models.CharField(blank=True, max_length=16)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("withdrawn", "Withdrawn")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("source_response_id", models.UUIDField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_members_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_members",
                        to="teams.teamgroup",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_members",
                        to="teams.institution",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entries",
                        to="teams.person",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_members",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "teams_roster_member",
            },
        ),
        migrations.CreateModel(
            name="TeamStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, default="in_charge", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams_in_charge",
                        to="teams.rostermember",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_staff",
                        to="organizations.organization",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "teams_team_staff",
            },
        ),
        migrations.AddIndex(
            model_name="rostermember",
            index=models.Index(
                fields=["tournament", "institution", "kind"],
                name="roster_trn_inst_kind_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rostermember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tournament", "institution", "person"),
                name="unique_roster_person_per_institution",
            ),
        ),
        migrations.AddIndex(
            model_name="teamstaff",
            index=models.Index(fields=["member"], name="team_staff_member_idx"),
        ),
        migrations.AddConstraint(
            model_name="teamstaff",
            constraint=models.UniqueConstraint(
                fields=("team", "member"), name="unique_staff_per_team"
            ),
        ),
    ]
