# Generated by Django 5.1.15 on 2026-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_rostermember_teamstaff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='team_code_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institution',
            name='team_code_prev_hash',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institution',
            name='team_code_prev_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
