# Generated by Django 5.1.15 on 2026-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_institution_team_code_enc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
