# Generated by Django 5.1.15 on 2026-08-03 03:28

import django.db.models.deletion
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0006_court'),
        ('organizations', '0006_organization_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtStream',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('watch_url', models.URLField(blank=True, max_length=500)),
                ('yt_stream_id', models.CharField(blank=True, max_length=64)),
                ('yt_stream_key', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='fixtures.court')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_streams', to='organizations.organization')),
            ],
            options={
                'db_table': 'streaming_court_stream',
            },
        ),
        migrations.CreateModel(
            name='CourtBroadcast',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('yt_video_id', models.CharField(blank=True, max_length=64)),
                ('actual_start_utc', models.DateTimeField(blank=True, null=True)),
                ('lifecycle', models.CharField(choices=[('created', 'Created'), ('ready', 'Ready'), ('live', 'Live'), ('complete', 'Complete'), ('errored', 'Errored')], default='created', max_length=16)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='fixtures.court')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_broadcasts', to='organizations.organization')),
            ],
            options={
                'db_table': 'streaming_court_broadcast',
                'indexes': [models.Index(fields=['court', 'day'], name='broadcast_court_day_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('court', 'day'), name='unique_broadcast_per_court_day')],
            },
        ),
    ]
