# Generated by Django 5.1.15 on 2026-08-04 18:36

import django.db.models.deletion
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0006_court'),
        ('matches', '0017_match_court_match_match_court_time_idx'),
        ('organizations', '0006_organization_school_profile'),
        ('streaming', '0001_initial'),
        ('tournaments', '0010_tournament_season_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamLink',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('match', 'Match'), ('court_day', 'Court, for one day'), ('category', 'Sport category')], db_index=True, max_length=16)),
                ('day', models.DateField(blank=True, null=True)),
                ('leaf_key', models.CharField(blank=True, default='', max_length=160)),
                ('watch_url', models.URLField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_links', to='fixtures.court')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_links', to='matches.match')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_links', to='organizations.organization')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_links', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'streaming_stream_link',
                'indexes': [models.Index(fields=['court', 'day'], name='stream_link_court_day_idx'), models.Index(fields=['tournament', 'leaf_key'], name='stream_link_leaf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('scope', 'match')), fields=('match',), name='unique_stream_link_per_match'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('scope', 'court_day')), fields=('court', 'day'), name='unique_stream_link_per_court_day'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('scope', 'category')), fields=('tournament', 'leaf_key'), name='unique_stream_link_per_category'), models.CheckConstraint(condition=models.Q(models.Q(('court__isnull', True), ('day__isnull', True), ('leaf_key', ''), ('match__isnull', False), ('scope', 'match')), models.Q(('court__isnull', False), ('day__isnull', False), ('leaf_key', ''), ('match__isnull', True), ('scope', 'court_day')), models.Q(('court__isnull', True), ('day__isnull', True), ('match__isnull', True), ('scope', 'category'), ('tournament__isnull', False), models.Q(('leaf_key', ''), _negated=True)), _connector='OR'), name='stream_link_scope_target_matches_scope')],
            },
        ),
    ]
