# Generated by Django 5.1.15 on 2026-07-02 09:03

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0012_match_stage_no'),
        ('organizations', '0004_alter_admininvitation_status'),
        ('teams', '0009_institution_team_code_hash_and_more'),
        ('tournaments', '0007_tournament_draw_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('badge_key', models.CharField(max_length=64)),
                ('leaf_key', models.CharField(blank=True, max_length=200)),
                ('stage_no', models.IntegerField(default=0)),
                ('group_label', models.CharField(blank=True, max_length=40)),
                ('subject_type', models.CharField(choices=[('team', 'Team'), ('player', 'Player')], default='team', max_length=12)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=350)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='matches.match')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='organizations.organization')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='teams.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='tournaments.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament', 'badge_key'], name='badges_badg_tournam_095094_idx'), models.Index(fields=['team'], name='badges_badg_team_id_c71368_idx'), models.Index(fields=['player'], name='badges_badg_player__49261f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('tournament', 'dedupe_key'), name='uniq_active_badge_award')],
            },
        ),
    ]
