# Generated by Django 5.1.15 on 2026-08-26 00:50

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_organization_school_profile'),
        ('tournaments', '0013_tournament_awards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_albums', to='organizations.organization')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_albums', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentVideo',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='organizations.organization')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.videoalbum')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videoalbum',
            index=models.Index(fields=['tournament', 'position'], name='video_album_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentvideo',
            index=models.Index(fields=['album', 'position'], name='video_item_ord_idx'),
        ),
    ]
