# Generated by Django 5.1.15 on 2026-08-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_backfill_crests'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentvideo',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='videos', to='teams.institution'),
        ),
        migrations.AddField(
            model_name='tournamentvideo',
            name='played_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentvideo',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
