# Generated by Django 5.1.15 on 2026-08-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_tournamentvideo_institutions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentvideo',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videoalbum',
            options={'ordering': ['position', '-created_at']},
        ),
    ]
