# Generated by Django 5.1.15 on 2026-05-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super-admin"),
                            ("admin", "Admin"),
                            ("co_organizer", "Co-organizer"),
                            ("game_coordinator", "Game coordinator"),
                            ("match_scorer", "Match scorer"),
                            ("referee", "Referee"),
                            ("team_manager", "Team manager"),
                            ("system", "System (auto-transition)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("deleted_user_handle", models.CharField(blank=True, max_length=64)),
                ("impersonating_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "tournament_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("match_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("target_type", models.CharField(db_index=True, max_length=64)),
                ("target_id", models.UUIDField(db_index=True)),
                ("payload_before", models.JSONField(blank=True, null=True)),
                ("payload_after", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "-created_at"],
                        name="audit_org_created_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"],
                        name="audit_target_created_idx",
                    ),
                    models.Index(
                        fields=["actor_user", "-created_at"],
                        name="audit_actor_created_idx",
                    ),
                ],
            },
        ),
    ]
