/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/auth/2fa/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_2fa_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/2fa/disable/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_2fa_disable_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/2fa/enroll/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_2fa_enroll_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/2fa/recovery_codes:regenerate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_2fa_recovery_codes:regenerate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/password-reset-complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_password_reset_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/password-reset-request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_password_reset_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/password_reset_complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_password_reset_complete_create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/password_reset_request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_password_reset_request_create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/reauth/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_reauth_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/signup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Public Path B signup (v1Users.md §2.3).
         *
         *     Creates a User + a pending-review Organization + a pending Admin
         *     membership in one atomic transaction. Path A (invite-accept) is
         *     handled by ``apps.organizations.views.invitation_accept`` and is
         *     NOT routed through here — invited users are joining an existing
         *     Org, not creating one.
         *
         *     Idempotency: clients may send a UUID ``event_id``; replay returns
         *     200 (existing record) instead of 201 (newly created), per
         *     architectural invariant 3.
         *
         *     Rate limit: ``SignupRateThrottle`` enforces 3/hr/IP per B.11.
         */
        post: operations["accounts_auth_signup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/verify_email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_auth_verify_email_create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounts_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["accounts_me_partial_update"];
        trace?: never;
    };
    "/api/accounts/users/{user_id}:soft_delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accounts_users_:soft_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/orgs/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cursor-paginated, org-scoped audit event feed. Read-only. Module-gated by `org.audit_log`. */
        get: operations["audit_orgs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit feedback from any authenticated user. Body is PII-redacted at the service layer (B.11). Throttled to 10/hr/user. */
        post: operations["feedback_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations:accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/invitations:accept/
         *
         *     Public path BUT the accepting user must be authenticated (otherwise
         *     we 401 with a redirect hint).
         */
        post: operations["invitations:accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET: list orgs the user has any active membership in.
         *     POST: super-admin only — create a new Organization in pending_review.
         */
        get: operations["orgs_list"];
        put?: never;
        /**
         * @description GET: list orgs the user has any active membership in.
         *     POST: super-admin only — create a new Organization in pending_review.
         */
        post: operations["orgs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug_or_uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET / PATCH on /api/orgs/{slug_or_uuid}/.
         *
         *     On GET with a slug match in `SlugRedirect`, returns a 301 with
         *     Location pointing at the canonical /api/orgs/{uuid}/.
         */
        get: operations["orgs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET / PATCH on /api/orgs/{slug_or_uuid}/.
         *
         *     On GET with a slug match in `SlugRedirect`, returns a 301 with
         *     Location pointing at the canonical /api/orgs/{uuid}/.
         */
        patch: operations["orgs_partial_update"];
        trace?: never;
    };
    "/api/orgs/{slug}/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET / POST /api/orgs/{slug}/invitations/ */
        get: operations["orgs_invitations_list"];
        put?: never;
        /** @description GET / POST /api/orgs/{slug}/invitations/ */
        post: operations["orgs_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/invitations/{invitation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description DELETE /api/orgs/{slug}/invitations/{invitation_id}/
         *
         *     Plain DELETE = revoke. Mirrors the AIP-136
         *     ``{uuid}/invitations/{id}:revoke/`` colon verb but uses the simpler
         *     REST shape the SPA expects.
         */
        delete: operations["orgs_invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/orgs/{slug}/members/
         *
         *     Returns one row per user (not per membership). Multiple membership
         *     rows for the same user (e.g. admin + co_organizer) are collapsed:
         *     ``roles`` is the distinct list, ``joined_at`` is MIN(created_at),
         *     ``is_org_owner`` is OR across the user's rows.
         */
        get: operations["orgs_members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/ownership/transfer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/orgs/{slug}/ownership/transfer/
         *
         *     Slug-routed proxy of the AIP-136
         *     ``{uuid}:transfer_ownership/`` colon verb.
         */
        post: operations["orgs_ownership_transfer_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_invitations_list_2"];
        put?: never;
        post: operations["orgs_invitations_create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}/invitations/{invitation_id}:revoke/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orgs_invitations_:revoke_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Module-gated by `org.member_directory` — defaults to admin /
         *     co_organizer / game_coordinator per the v1Users.md catalog. A
         *     per-user `MembershipModuleGrant` deny override revokes access even
         *     for those role defaults.
         */
        get: operations["orgs_members_list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}/members/{membership_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["orgs_members_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}:archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner or super-admin only. */
        post: operations["orgs_:archive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}:change_slug/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/orgs/{uuid}:change_slug/ */
        post: operations["orgs_:change_slug_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}:suspend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orgs_:suspend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}:transfer_ownership/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Current owner only. Atomic swap. */
        post: operations["orgs_:transfer_ownership_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{uuid}:unsuspend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orgs_:unsuspend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/invitations/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/orgs/invitations/accept/
         *
         *     Path alias of ``/api/invitations:accept/``. Same body, same logic.
         */
        post: operations["orgs_invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/me/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the effective module set for the requesting user in the given Org. */
        get: operations["permissions_me_modules_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all modules in the catalog. */
        get: operations["permissions_modules_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/orgs/{org_uuid}/users/{user_uuid}/grants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all grant rows + computed default-on modules for a user in an org. */
        get: operations["permissions_orgs_users_grants_list"];
        /** @description Replace grants atomically. Accepts EITHER `{grants: [{module, state}], reason}` (existing shape) OR `{cells: {module_code: state}, reason, event_id?}` (SPA matrix shape). If both keys are present, `cells` wins. */
        put: operations["permissions_orgs_users_grants_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/orgs/{slug}/grants/matrix/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Aggregate override matrix: for every active member in the org, list each module's role-default truth and explicit override state. */
        get: operations["permissions_orgs_grants_matrix_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/orgs/{slug}/me/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Slug-routed alias of /me/modules/?org=<uuid>. Returns effective module set for the authenticated user in the org identified by slug. */
        get: operations["permissions_orgs_me_modules_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/orgs/{slug}/users/{user_uuid}/grants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Slug-routed alias for GET /grants/ — same response shape. */
        get: operations["permissions_orgs_users_grants_list_2"];
        /** @description Slug-routed alias for PUT /grants/. Accepts EITHER the `{grants: [{module, state}], reason}` shape or the SPA matrix `{cells: {module: state}, reason, event_id?}` shape. */
        put: operations["permissions_orgs_users_grants_update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/sports/`` — list every sport in the catalog.
         *
         *     Unfiltered by default; supports ``?status=`` and ``?category=`` query
         *     params for convenience. Always ordered by ``display_order`` ascending
         *     (the model's default ordering).
         */
        get: operations["sports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/sports/<code>/`` — fetch a single sport by code. */
        get: operations["sports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitation: {
            token: string;
        };
        /**
         * @description Read-side serializer. Surfaces effective_status (computed) which
         *     flips pending→expired when expires_at is in the past, even if the
         *     DB row hasn't been swept yet (we don't run a cron — read-time
         *     materialization).
         */
        AdminInvitation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly organization: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["RoleEnum"];
            /** @default pending */
            readonly status: components["schemas"]["AdminInvitationStatusEnum"];
            readonly effective_status: string;
            /** Format: date-time */
            readonly expires_at: string;
            /** Format: date-time */
            readonly accepted_at: string | null;
            /** Format: date-time */
            readonly revoked_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly invited_by: string | null;
        };
        /**
         * @description Body shape accepted by both the UUID-routed and slug-routed
         *     invitation-create endpoints.
         *
         *     Either ``role`` (single string, legacy) or ``roles`` (list, sent by
         *     the SPA) may be given. ``event_id`` is the optional idempotency key
         *     (UUID).
         */
        AdminInvitationCreate: {
            /** Format: email */
            email: string;
            role?: components["schemas"]["RoleEnum"];
            roles?: components["schemas"]["RolesEnum"][];
            /** Format: uuid */
            event_id?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `accepted` - Accepted
         *     * `expired` - Expired
         *     * `revoked` - Revoked
         * @enum {string}
         */
        AdminInvitationStatusEnum: "pending" | "accepted" | "expired" | "revoked";
        Archive: {
            reason: string;
        };
        /**
         * @description Read-only serializer for AuditEvent rows.
         *
         *     Includes a denormalized ``actor_email_at_time`` (the actor user's
         *     current email — there is no historical snapshot in v1A; B.5 lists
         *     ``deleted_user_handle`` as the post-deletion fallback). ``payload``
         *     is the merged ``payload_after`` (creation-style events) or
         *     ``payload_before`` -> ``payload_after`` diff for mutating events.
         */
        AuditEvent: {
            /** Format: uuid */
            readonly id: string;
            readonly event_type: string;
            /** Format: uuid */
            readonly actor_id: string | null;
            readonly actor_email_at_time: string | null;
            /** Format: uuid */
            readonly target_id: string;
            readonly target_type: string;
            readonly target_label: string | null;
            readonly payload: {
                [key: string]: unknown;
            } | null;
            readonly reason: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Cursor-paginated response shape for the audit list endpoint. */
        AuditEventListResponse: {
            results: components["schemas"]["AuditEvent"][];
            next_cursor?: string | null;
            previous_cursor?: string | null;
        };
        /** @description PUT body for /grants/ — replace all grants atomically. */
        BulkGrants: {
            grants: components["schemas"]["GrantInput"][];
            reason: string;
        };
        ChangeSlug: {
            new_slug: string;
        };
        /** @description Response shape for GET /me/modules/. */
        EffectiveModules: {
            modules: string[];
        };
        /**
         * @description Request body for ``POST /api/feedback/submit/``.
         *
         *     Frontend wires the feedback widget (v1Users.md A.2
         *     ``personal.feedback_widget``) to this endpoint. Body is PII-redacted
         *     at the service layer (B.11) so screenshots / page URLs that may
         *     contain emails or recovery codes are stripped before INSERT.
         *
         *     ``event_id`` is an optional client-supplied UUID for idempotency
         *     (PRD invariant 3). When supplied, re-submitting the same id
         *     returns the existing row (200 instead of 201).
         */
        FeedbackSubmit: {
            message: string;
            page_url?: string;
            screenshot_data_uri?: string;
            /** @default other */
            category: components["schemas"]["FeedbackSubmitCategoryEnum"];
            subject?: string;
            /** Format: uuid */
            event_id?: string;
        };
        /**
         * @description * `bug` - Bug
         *     * `feature_request` - Feature request
         *     * `complaint` - Complaint
         *     * `praise` - Praise
         *     * `other` - Other
         * @enum {string}
         */
        FeedbackSubmitCategoryEnum: "bug" | "feature_request" | "complaint" | "praise" | "other";
        /** @description Response body for the public submit endpoint. */
        FeedbackSubmitResponse: {
            /** Format: uuid */
            id: string;
        };
        /** @description Single (module, state) pair used inside the bulk grants PUT body. */
        GrantInput: {
            module: string;
            state: components["schemas"]["StateEnum"];
        };
        /** @description A single MembershipModuleGrant row, with module code denormalized. */
        GrantRow: {
            /** Format: uuid */
            readonly id: string;
            readonly module_code: string;
            readonly state: components["schemas"]["StateEnum"];
            readonly reason: string;
            /** Format: uuid */
            readonly granted_by: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
            totp_code?: string;
        };
        /** @description One member row in the matrix `members` array. */
        MatrixMember: {
            user_id: string;
            user_email: string;
            user_full_name: string;
            roles: string[];
            cells: {
                [key: string]: string;
            };
            role_defaults: {
                [key: string]: boolean;
            };
        };
        /** @description One module row in the matrix `modules` array. */
        MatrixModule: {
            key: string;
            scope: string;
            label: string;
            description: string;
        };
        /** @description Top-level response shape for the matrix endpoint. */
        MatrixResponse: {
            modules: components["schemas"]["MatrixModule"][];
            members: components["schemas"]["MatrixMember"][];
        };
        /**
         * @description Used by GET/PATCH /api/accounts/me/.
         *
         *     Read shape includes `is_superuser`, `memberships[]`, and
         *     `last_active_org_slug` so the SPA can route directly to a dashboard
         *     without a second round-trip to /api/orgs/.
         */
        Me: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            /** Full name */
            name?: string;
            readonly is_superuser: boolean;
            readonly has_2fa_enrolled: boolean;
            /** Format: date-time */
            readonly twofa_enrolled_at: string | null;
            /** Format: date-time */
            readonly email_verified_at: string | null;
            /** Format: uuid */
            last_active_org_id?: string | null;
            readonly last_active_org_slug: string | null;
            readonly memberships: components["schemas"]["MembershipSummary"][];
            /** Format: date-time */
            readonly deleted_at: string | null;
        };
        /**
         * @description One per-org membership row consumed by the SPA bootstrap.
         *
         *     Aggregated across the user's (potentially multiple) role rows in
         *     the same org so the SPA can render one switcher entry per org and
         *     a roles-array for in-org role-view toggling (§2.7).
         */
        MembershipSummary: {
            /** Format: uuid */
            org_id: string;
            org_slug: string;
            org_name: string;
            roles: string[];
            is_org_owner: boolean;
            effective_modules: string[];
        };
        /** @description Serializer for the module catalog (read-only, public-ish). */
        Module: {
            /** Format: uuid */
            readonly id: string;
            readonly code: string;
            readonly name: string;
            readonly description: string;
            readonly category: string;
            readonly default_for_roles: unknown;
        };
        /**
         * @description Shape returned by ``GET /api/orgs/{slug}/members/``.
         *
         *     Pre-aggregated by the view: one entry per user with roles[] (distinct
         *     role strings from all that user's active membership rows in this
         *     org), the earliest joined_at, and OR(is_org_owner) across rows.
         */
        OrgMemberDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            full_name: string;
            roles: string[];
            is_org_owner: boolean;
            /** Format: date-time */
            joined_at: string;
            is_active: boolean;
        };
        Organization: {
            /** Format: uuid */
            readonly id: string;
            slug: string;
            name: string;
            readonly status: components["schemas"]["OrganizationStatusEnum"];
            time_zone?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly archived_at: string | null;
            /** Format: date-time */
            readonly suspended_at: string | null;
            readonly suspended_reason: string;
        };
        OrganizationCreate: {
            slug: string;
            name: string;
            /** @default Asia/Kolkata */
            time_zone: string;
        };
        OrganizationMembership: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user: string;
            /** Format: uuid */
            readonly organization: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly is_org_owner: boolean;
            /** @default true */
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly removed_at: string | null;
        };
        /**
         * @description * `pending_review` - Pending review
         *     * `active` - Active
         *     * `suspended` - Suspended
         *     * `archived` - Archived
         *     * `orphaned` - Orphaned
         * @enum {string}
         */
        OrganizationStatusEnum: "pending_review" | "active" | "suspended" | "archived" | "orphaned";
        PasswordResetComplete: {
            token: string;
            new_password: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @description Used by GET/PATCH /api/accounts/me/.
         *
         *     Read shape includes `is_superuser`, `memberships[]`, and
         *     `last_active_org_slug` so the SPA can route directly to a dashboard
         *     without a second round-trip to /api/orgs/.
         */
        PatchedMe: {
            /** Format: uuid */
            readonly id?: string;
            /**
             * Email address
             * Format: email
             */
            readonly email?: string;
            /** Full name */
            name?: string;
            readonly is_superuser?: boolean;
            readonly has_2fa_enrolled?: boolean;
            /** Format: date-time */
            readonly twofa_enrolled_at?: string | null;
            /** Format: date-time */
            readonly email_verified_at?: string | null;
            /** Format: uuid */
            last_active_org_id?: string | null;
            readonly last_active_org_slug?: string | null;
            readonly memberships?: components["schemas"]["MembershipSummary"][];
            /** Format: date-time */
            readonly deleted_at?: string | null;
        };
        PatchedOrganizationUpdate: {
            name?: string;
            time_zone?: string;
        };
        Reauth: {
            password: string;
        };
        RevokeInvitation: {
            reason?: string;
        };
        /**
         * @description * `admin` - Admin
         *     * `co_organizer` - Co-organizer
         *     * `game_coordinator` - Game coordinator
         *     * `match_scorer` - Match scorer
         *     * `referee` - Referee
         *     * `team_manager` - Team manager
         * @enum {string}
         */
        RoleEnum: "admin" | "co_organizer" | "game_coordinator" | "match_scorer" | "referee" | "team_manager";
        /**
         * @description * `admin` - Admin
         *     * `co_organizer` - Co-organizer
         *     * `game_coordinator` - Game coordinator
         *     * `match_scorer` - Match scorer
         *     * `referee` - Referee
         *     * `team_manager` - Team manager
         * @enum {string}
         */
        RolesEnum: "admin" | "co_organizer" | "game_coordinator" | "match_scorer" | "referee" | "team_manager";
        /**
         * @description Public self-signup payload (v1Users.md §2.3 Path B).
         *
         *     The signup endpoint creates a User AND a pending-review Organization
         *     plus a pending Admin membership in a single atomic transaction. The
         *     optional ``org_name`` lets the user choose a display name for their
         *     new tenant; if omitted, it is derived from the email local-part.
         *
         *     ``event_id`` (optional, client-generated UUID) is honored for
         *     idempotent retries per architectural invariant 3 — re-submitting the
         *     same ``event_id`` short-circuits and returns the existing record.
         */
        Signup: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
            org_name?: string;
            /** Format: uuid */
            event_id?: string;
        };
        SoftDelete: {
            reason?: string;
        };
        Sport: {
            /** Format: uuid */
            readonly id: string;
            readonly code: string;
            readonly name: string;
            readonly category: components["schemas"]["SportCategoryEnum"];
            readonly status: components["schemas"]["SportStatusEnum"];
            readonly description: string;
            readonly indigenous_to: string;
            readonly is_team_sport: boolean;
            readonly is_individual_sport: boolean;
            readonly icon: string;
            readonly display_order: number;
        };
        /**
         * @description * `team` - Team
         *     * `individual` - Individual
         *     * `racket` - Racket
         *     * `combat` - Combat / Martial arts
         *     * `athletics` - Athletics
         *     * `aquatics` - Aquatics
         *     * `gymnastics` - Gymnastics
         *     * `strength` - Strength sports
         *     * `shooting` - Shooting / Archery
         *     * `mind` - Mind sports
         *     * `indigenous` - Indigenous / Traditional
         *     * `adventure` - Adventure / Outdoor
         *     * `other` - Other
         * @enum {string}
         */
        SportCategoryEnum: "team" | "individual" | "racket" | "combat" | "athletics" | "aquatics" | "gymnastics" | "strength" | "shooting" | "mind" | "indigenous" | "adventure" | "other";
        /**
         * @description * `planned` - Planned
         *     * `coming_soon` - Coming soon
         *     * `active` - Active
         *     * `deprecated` - Deprecated
         * @enum {string}
         */
        SportStatusEnum: "planned" | "coming_soon" | "active" | "deprecated";
        /**
         * @description * `default` - Default (no override)
         *     * `grant` - Grant (force on)
         *     * `deny` - Deny (force off)
         * @enum {string}
         */
        StateEnum: "default" | "grant" | "deny";
        Suspend: {
            reason: string;
        };
        /**
         * @description Accepts either ``new_owner_user_id`` (canonical) or ``to_user_id``
         *     (frontend alias). At least one must be present.
         */
        TransferOwnership: {
            /** Format: uuid */
            new_owner_user_id?: string;
            /** Format: uuid */
            to_user_id?: string;
            reason?: string;
            /** Format: uuid */
            event_id?: string;
            conflict_acknowledged?: boolean;
        };
        TwoFAConfirm: {
            code: string;
        };
        TwoFAConfirmResponse: {
            recovery_codes: string[];
        };
        TwoFADisable: {
            reason?: string;
        };
        TwoFAEnrollResponse: {
            otpauth_uri: string;
            qr_data_uri: string;
            /** Format: uuid */
            device_id: string;
        };
        VerifyEmail: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_auth_2fa_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFAConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["TwoFAConfirm"];
                "multipart/form-data": components["schemas"]["TwoFAConfirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFAConfirmResponse"];
                };
            };
        };
    };
    accounts_auth_2fa_disable_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TwoFADisable"];
                "application/x-www-form-urlencoded": components["schemas"]["TwoFADisable"];
                "multipart/form-data": components["schemas"]["TwoFADisable"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_2fa_enroll_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFAEnrollResponse"];
                };
            };
        };
    };
    "accounts_auth_2fa_recovery_codes:regenerate_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFAConfirmResponse"];
                };
            };
        };
    };
    accounts_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_password_reset_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetComplete"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetComplete"];
                "multipart/form-data": components["schemas"]["PasswordResetComplete"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_password_reset_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_password_reset_complete_create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetComplete"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetComplete"];
                "multipart/form-data": components["schemas"]["PasswordResetComplete"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_password_reset_request_create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_reauth_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reauth"];
                "application/x-www-form-urlencoded": components["schemas"]["Reauth"];
                "multipart/form-data": components["schemas"]["Reauth"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_signup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Signup"];
                "application/x-www-form-urlencoded": components["schemas"]["Signup"];
                "multipart/form-data": components["schemas"]["Signup"];
            };
        };
        responses: {
            /** @description Pending account; check email. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_auth_verify_email_create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    accounts_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMe"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMe"];
                "multipart/form-data": components["schemas"]["PatchedMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    "accounts_users_:soft_delete_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SoftDelete"];
                "application/x-www-form-urlencoded": components["schemas"]["SoftDelete"];
                "multipart/form-data": components["schemas"]["SoftDelete"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    audit_orgs_retrieve: {
        parameters: {
            query?: {
                actor_id?: string;
                cursor?: string;
                event_type?: string;
                from?: string;
                limit?: number;
                to?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
        };
    };
    feedback_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSubmit"];
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackSubmit"];
                "multipart/form-data": components["schemas"]["FeedbackSubmit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSubmitResponse"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSubmitResponse"];
                };
            };
        };
    };
    "invitations:accept_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitation"];
                "application/x-www-form-urlencoded": components["schemas"]["AcceptInvitation"];
                "multipart/form-data": components["schemas"]["AcceptInvitation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMembership"];
                };
            };
        };
    };
    orgs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    orgs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["OrganizationCreate"];
                "multipart/form-data": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    orgs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug_or_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    orgs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug_or_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrganizationUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOrganizationUpdate"];
                "multipart/form-data": components["schemas"]["PatchedOrganizationUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    orgs_invitations_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInvitation"][];
                };
            };
        };
    };
    orgs_invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminInvitationCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminInvitationCreate"];
                "multipart/form-data": components["schemas"]["AdminInvitationCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInvitation"];
                };
            };
        };
    };
    orgs_invitations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orgs_members_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMemberDetail"][];
                };
            };
        };
    };
    orgs_ownership_transfer_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TransferOwnership"];
                "application/x-www-form-urlencoded": components["schemas"]["TransferOwnership"];
                "multipart/form-data": components["schemas"]["TransferOwnership"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    orgs_invitations_list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInvitation"][];
                };
            };
        };
    };
    orgs_invitations_create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminInvitationCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminInvitationCreate"];
                "multipart/form-data": components["schemas"]["AdminInvitationCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInvitation"];
                };
            };
        };
    };
    "orgs_invitations_:revoke_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RevokeInvitation"];
                "application/x-www-form-urlencoded": components["schemas"]["RevokeInvitation"];
                "multipart/form-data": components["schemas"]["RevokeInvitation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInvitation"];
                };
            };
        };
    };
    orgs_members_list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMembership"][];
                };
            };
        };
    };
    orgs_members_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "orgs_:archive_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Archive"];
                "application/x-www-form-urlencoded": components["schemas"]["Archive"];
                "multipart/form-data": components["schemas"]["Archive"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    "orgs_:change_slug_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSlug"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangeSlug"];
                "multipart/form-data": components["schemas"]["ChangeSlug"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    "orgs_:suspend_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Suspend"];
                "application/x-www-form-urlencoded": components["schemas"]["Suspend"];
                "multipart/form-data": components["schemas"]["Suspend"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    "orgs_:transfer_ownership_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TransferOwnership"];
                "application/x-www-form-urlencoded": components["schemas"]["TransferOwnership"];
                "multipart/form-data": components["schemas"]["TransferOwnership"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    "orgs_:unsuspend_create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    orgs_invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitation"];
                "application/x-www-form-urlencoded": components["schemas"]["AcceptInvitation"];
                "multipart/form-data": components["schemas"]["AcceptInvitation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMembership"];
                };
            };
        };
    };
    permissions_me_modules_retrieve: {
        parameters: {
            query: {
                /** @description Organization UUID */
                org: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveModules"];
                };
            };
        };
    };
    permissions_modules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Module"][];
                };
            };
        };
    };
    permissions_orgs_users_grants_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_uuid: string;
                user_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantRow"][];
                };
            };
        };
    };
    permissions_orgs_users_grants_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_uuid: string;
                user_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkGrants"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkGrants"];
                "multipart/form-data": components["schemas"]["BulkGrants"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantRow"][];
                };
            };
        };
    };
    permissions_orgs_grants_matrix_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixResponse"];
                };
            };
        };
    };
    permissions_orgs_me_modules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveModules"];
                };
            };
        };
    };
    permissions_orgs_users_grants_list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                user_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantRow"][];
                };
            };
        };
    };
    permissions_orgs_users_grants_update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                user_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkGrants"];
                "application/x-www-form-urlencoded": components["schemas"]["BulkGrants"];
                "multipart/form-data": components["schemas"]["BulkGrants"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantRow"][];
                };
            };
        };
    };
    sports_list: {
        parameters: {
            query?: {
                /** @description Filter by category band (team/racket/combat/etc). */
                category?: string;
                /** @description Filter by lifecycle status (planned/coming_soon/active/deprecated). */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
        };
    };
    sports_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
        };
    };
}
