# Generated by Django 5.1.15 on 2026-06-05 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0003_remove_admininvitation_unique_pending_invite_per_email_per_org_and_more",
        ),
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stage", models.CharField(blank=True, max_length=40)),
                ("group_label", models.CharField(blank=True, max_length=80)),
                ("round_no", models.PositiveSmallIntegerField(default=1)),
                ("match_no", models.PositiveIntegerField(default=0)),
                ("home_source", models.JSONField(blank=True, default=dict)),
                ("away_source", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=120)),
                ("inputs_hash", models.CharField(blank=True, max_length=64)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="away_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="organizations.organization",
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_scoring",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "matches_match",
                "indexes": [
                    models.Index(
                        fields=["tournament", "status"], name="match_trn_status_idx"
                    ),
                    models.Index(
                        fields=["tournament", "group_label"], name="match_trn_group_idx"
                    ),
                ],
            },
        ),
    ]
