# Generated by Django 5.1.15 on 2026-06-05 09:58

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
        (
            "organizations",
            "0003_remove_admininvitation_unique_pending_invite_per_email_per_org_and_more",
        ),
        ("teams", "0003_registrationlink_expires_at_and_more"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="current_period",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("half_time", "Half time"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("postponed", "Postponed"),
                    ("abandoned", "Abandoned"),
                    ("walkover", "Walkover"),
                ],
                db_index=True,
                default="scheduled",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_no", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("goal", "Goal"),
                            ("own_goal", "Own goal"),
                            ("penalty_scored", "Penalty scored"),
                            ("penalty_missed", "Penalty missed"),
                            ("yellow_card", "Yellow card"),
                            ("red_card", "Red card"),
                            ("substitution", "Substitution"),
                            ("period_start", "Period start"),
                            ("period_end", "Period end"),
                            ("void", "Void (reversal)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("period", models.CharField(blank=True, max_length=24)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("event_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="matches.match",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_events",
                        to="teams.player",
                    ),
                ),
                (
                    "related_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_events_related",
                        to="teams.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_events",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "voids",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_by",
                        to="matches.matchevent",
                    ),
                ),
            ],
            options={
                "db_table": "matches_match_event",
                "ordering": ["match", "sequence_no"],
                "indexes": [
                    models.Index(
                        fields=["match", "sequence_no"], name="event_match_seq_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "sequence_no"),
                        name="unique_event_seq_per_match",
                    )
                ],
            },
        ),
    ]
