# Generated by Django 5.1.15 on 2026-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_match_current_period_alter_match_status_matchevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("goal", "Goal"),
                    ("own_goal", "Own goal"),
                    ("penalty_scored", "Penalty scored"),
                    ("penalty_missed", "Penalty missed"),
                    ("penalty_awarded", "Penalty awarded"),
                    ("shot", "Shot"),
                    ("save", "Save"),
                    ("corner", "Corner"),
                    ("free_kick", "Free kick"),
                    ("foul", "Foul"),
                    ("yellow_card", "Yellow card"),
                    ("red_card", "Red card"),
                    ("substitution", "Substitution"),
                    ("period_start", "Period start"),
                    ("period_end", "Period end"),
                    ("void", "Void (reversal)"),
                ],
                max_length=20,
            ),
        ),
    ]
