# Generated by Django 5.1.15 on 2026-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_lineup_lineupentry_matchincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='set_scores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
