# Generated by Django 5.1.15 on 2026-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_set_scores_match_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='leaf_key',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
    ]
