# Generated by Django 5.1.15 on 2026-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_leaf_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_pens',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_pens',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
