# Generated by Django 5.1.15 on 2026-06-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_away_pens_match_home_pens'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
