# Generated by Django 5.1.15 on 2026-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
