# Generated by Django 5.1.15 on 2026-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_called_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
