# Generated by Django 5.1.15 on 2026-06-26 11:01

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_ended_at_match_started_at'),
        ('organizations', '0004_alter_admininvitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOfficial',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('referee', 'Referee'), ('assistant', 'Assistant referee'), ('fourth', 'Fourth official'), ('umpire', 'Umpire'), ('commissioner', 'Match commissioner')], max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='assigned', max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='matches.match')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_officials', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_officiating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_match_official',
                'ordering': ['match', 'role'],
                'indexes': [models.Index(fields=['match'], name='official_match_idx'), models.Index(fields=['user'], name='official_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'user'), name='unique_official_per_match')],
            },
        ),
    ]
