# Generated by Django 5.1.15 on 2026-06-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_matchofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage_no',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
