# Generated by Django 5.1.15 on 2026-07-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_match_stage_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupentry',
            name='positional_role',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
