# Generated by Django 5.1.15 on 2026-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_lineupentry_positional_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('own_goal', 'Own goal'), ('penalty_scored', 'Penalty scored'), ('penalty_missed', 'Penalty missed'), ('penalty_awarded', 'Penalty awarded'), ('shot', 'Shot'), ('save', 'Save'), ('corner', 'Corner'), ('free_kick', 'Free kick'), ('foul', 'Foul'), ('yellow_card', 'Yellow card'), ('red_card', 'Red card'), ('substitution', 'Substitution'), ('period_start', 'Period start'), ('period_end', 'Period end'), ('serve', 'Serve'), ('ace', 'Service ace'), ('service_fault', 'Service fault'), ('kill', 'Kill (spike)'), ('block', 'Block'), ('point', 'Rally point'), ('let', 'Let'), ('timeout', 'Timeout'), ('assist', 'Assist'), ('void', 'Void (reversal)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchofficial',
            name='role',
            field=models.CharField(choices=[('referee', 'Referee'), ('assistant', 'Assistant referee'), ('fourth', 'Fourth official'), ('umpire', 'Umpire'), ('commissioner', 'Match commissioner'), ('linesman', 'Linesman')], max_length=20),
        ),
    ]
