# Generated by Django 5.1.15 on 2026-07-04 08:57

import django.db.models.deletion
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_alter_matchevent_event_type'),
        ('organizations', '0006_organization_school_profile'),
        ('teams', '0010_schoolprofile_institution_school_profile_season_and_more'),
        ('tournaments', '0010_tournament_season_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rubber_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='rubber_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchTie',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('leaf_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('stage', models.CharField(blank=True, max_length=24)),
                ('group_label', models.CharField(blank=True, max_length=120)),
                ('format', models.JSONField(blank=True, default=dict)),
                ('home_rubbers_won', models.PositiveSmallIntegerField(default=0)),
                ('away_rubbers_won', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ties_away', to='teams.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ties_home', to='teams.team')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ties', to='organizations.organization')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ties', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'matches_tie',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubbers', to='matches.matchtie'),
        ),
    ]
