# Generated by Django 5.1.15 on 2026-08-03 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0006_court'),
        ('matches', '0016_match_rubber_kind_match_rubber_no_matchtie_match_tie'),
        ('organizations', '0006_organization_school_profile'),
        ('teams', '0010_schoolprofile_institution_school_profile_season_and_more'),
        ('tournaments', '0010_tournament_season_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='fixtures.court'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['court', 'scheduled_at'], name='match_court_time_idx'),
        ),
    ]
