# Generated by Django 5.1.15 on 2026-06-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0003_remove_admininvitation_unique_pending_invite_per_email_per_org_and_more",
        ),
        ("tournaments", "0002_tournament_constraints_tournament_rules_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=63)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("organization_registration", "Organization registration"),
                            ("team_registration", "Team registration"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        max_length=32,
                    ),
                ),
                ("schema", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("max_responses", models.PositiveIntegerField(blank=True, null=True)),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("confirmation_message", models.TextField(blank=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forms_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="organizations.organization",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "forms_form",
            },
        ),
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("form_version", models.PositiveIntegerField(default=1)),
                (
                    "respondent_email",
                    models.CharField(blank=True, db_index=True, max_length=254),
                ),
                (
                    "respondent_phone",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("respondent_name", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(blank=True, db_index=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=12,
                    ),
                ),
                ("event_id", models.UUIDField(blank=True, null=True)),
                ("mapped_entities", models.JSONField(blank=True, default=dict)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="forms.form",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_responses",
                        to="organizations.organization",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_responses",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "forms_response",
            },
        ),
        migrations.CreateModel(
            name="FormFileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.CharField(max_length=80)),
                (
                    "upload_ref",
                    models.UUIDField(
                        db_index=True,
                        default=apps.accounts.models.uuid7,
                        editable=False,
                    ),
                ),
                ("file", models.FileField(upload_to="form_uploads/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=127)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="forms.form",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_uploads",
                        to="organizations.organization",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="forms.formresponse",
                    ),
                ),
            ],
            options={
                "db_table": "forms_file_upload",
            },
        ),
        migrations.CreateModel(
            name="FormShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=128)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_submissions", models.PositiveIntegerField(blank=True, null=True)),
                ("submission_count", models.PositiveIntegerField(default=0)),
                ("bound_entity", models.JSONField(blank=True, default=dict)),
                ("prefill", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_share_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="forms.form",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_share_links",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "forms_share_link",
            },
        ),
        migrations.AddField(
            model_name="formresponse",
            name="submitted_via",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="forms.formsharelink",
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["tournament", "status"], name="form_trn_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tournament", "slug"),
                name="unique_form_slug_per_tournament",
            ),
        ),
        migrations.AddIndex(
            model_name="formresponse",
            index=models.Index(fields=["form", "status"], name="resp_form_status_idx"),
        ),
        migrations.AddIndex(
            model_name="formresponse",
            index=models.Index(
                fields=["form", "created_at"], name="resp_form_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="formresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_id__isnull", False)),
                fields=("form", "event_id"),
                name="unique_form_response_event_id",
            ),
        ),
    ]
