# Generated by Django 5.1.15 on 2026-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='stage',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
