# Generated by Django 5.1.15 on 2026-06-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_backfill_form_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfileupload',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
