# Generated by Django 5.1.15 on 2026-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_formfileupload_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("organization_registration", "Organization registration"),
                    ("participant_registration", "Participant registration"),
                    ("team_registration", "Team registration"),
                    ("generic", "Generic"),
                ],
                default="generic",
                max_length=32,
            ),
        ),
    ]
