# Generated by Django 5.1.15 on 2026-06-05 04:27

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0002_remove_organizationmembership_single_org_per_admin_user",
        ),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("registration_open", "Registration open"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("time_zone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("inputs_hash", models.CharField(blank=True, max_length=64)),
                ("last_manual_edit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournaments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournaments",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_tournament",
            },
        ),
        migrations.CreateModel(
            name="TournamentMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("co_organizer", "Co-organizer"),
                            ("game_coordinator", "Game coordinator"),
                            ("match_scorer", "Match scorer"),
                            ("referee", "Referee"),
                            ("team_manager", "Team manager"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournaments_membership",
            },
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["organization", "status"], name="trn_org_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "slug"),
                name="unique_tournament_slug_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentmembership",
            index=models.Index(
                fields=["tournament", "role", "status"], name="trnmem_t_role_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentmembership",
            index=models.Index(
                fields=["user", "status"], name="trnmem_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user", "tournament", "role"),
                name="unique_active_tournament_role",
            ),
        ),
    ]
