# Generated by Django 5.1.15 on 2026-06-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="constraints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tournament",
            name="rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tournament",
            name="rules_frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
