# Generated by Django 5.1.15 on 2026-06-08 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_admininvitation_status'),
        ('sports', '0001_initial'),
        ('tournaments', '0002_tournament_constraints_tournament_rules_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='stage',
            field=models.CharField(choices=[('setup', 'Setup'), ('org_registration', 'Institution registration'), ('team_registration', 'Team registration'), ('members', 'Members & roles'), ('fixtures', 'Fixtures'), ('ready', 'Ready')], db_index=True, default='setup', max_length=24),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stage_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['organization', 'stage'], name='trn_org_stage_idx'),
        ),
    ]
