# Generated by Django 5.1.15 on 2026-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_backfill_tournament_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='sports',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
