# Generated by Django 5.1.15 on 2026-06-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='scheduling_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
