# Generated by Django 5.1.15 on 2026-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_scheduling_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='draw_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
