# Generated by Django 5.1.15 on 2026-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_draw_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='starts_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
