# Generated by Django 5.1.15 on 2026-07-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_schoolprofile_institution_school_profile_season_and_more'),
        ('tournaments', '0009_backfill_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='season_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='teams.season'),
        ),
    ]
