# Generated by Django 5.1.15 on 2026-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_tournament_season_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="group_kind",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="tournament",
            name="scope",
            field=models.CharField(
                choices=[
                    ("inter_school", "Between schools"),
                    ("intra_school", "Within one school"),
                ],
                db_index=True,
                default="inter_school",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="stage",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("org_registration", "Institution registration"),
                    ("house_setup", "Houses & members"),
                    ("team_registration", "Team registration"),
                    ("members", "Members & roles"),
                    ("fixtures", "Fixtures"),
                    ("ready", "Ready"),
                ],
                db_index=True,
                default="setup",
                max_length=24,
            ),
        ),
    ]
