# Generated by Django 5.1.15 on 2026-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_tournament_group_kind_tournament_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="roster_mode",
            field=models.CharField(
                choices=[
                    ("inline", "Names typed on the team form"),
                    ("roster_first", "Participants first, then teams"),
                ],
                default="inline",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="stage",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("org_registration", "Institution registration"),
                    ("house_setup", "Houses & members"),
                    ("roster", "Participants"),
                    ("team_registration", "Team registration"),
                    ("members", "Members & roles"),
                    ("fixtures", "Fixtures"),
                    ("ready", "Ready"),
                ],
                db_index=True,
                default="setup",
                max_length=24,
            ),
        ),
    ]
