# Generated by Django 5.1.15 on 2026-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_roster_mode_alter_tournament_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='awards',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
