# Generated by Django 5.1.15 on 2026-05-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(db_index=True, default="", max_length=64),
                ),
                ("default_for_roles", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "permissions_module",
                "ordering": ["category", "code"],
                "indexes": [
                    models.Index(fields=["category"], name="perm_module_category_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipModuleGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("default", "Default (no override)"),
                            ("grant", "Grant (force on)"),
                            ("deny", "Deny (force off)"),
                        ],
                        default="default",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grants_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="permissions_app.module",
                    ),
                ),
            ],
            options={
                "db_table": "permissions_membership_module_grant",
                "indexes": [
                    models.Index(
                        fields=["user", "organization"], name="perm_grant_user_org_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "organization", "module"),
                        name="unique_grant_per_user_org_module",
                    )
                ],
            },
        ),
    ]
