# Generated by Django 5.1.15 on 2026-06-10 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions_app', '0001_initial'),
        ('tournaments', '0006_tournament_scheduling_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModuleGrant',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('default', 'Default (no override)'), ('grant', 'Grant (force on)'), ('deny', 'Deny (force off)')], default='default', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_grants_made', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_grants', to='permissions_app.module')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_grants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_module_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permissions_tournament_module_grant',
                'indexes': [models.Index(fields=['user', 'tournament'], name='perm_tgrant_user_trn_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tournament', 'module'), name='unique_grant_per_user_trn_module')],
            },
        ),
    ]
