# Generated by Django 5.1.15 on 2026-07-10 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models
import apps.lens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_organization_school_profile'),
        ('teams', '0010_schoolprofile_institution_school_profile_season_and_more'),
        ('tournaments', '0010_tournament_season_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LensCampaign',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Guest Lens', max_length=120)),
                ('tagline', models.CharField(default='36 Shots Challenge', max_length=120)),
                ('instructions', models.TextField(blank=True, default="Scan your school's QR pass to open the upload page. Capture the event from your school's point of view and upload your best shots from your own phone. The host reviews every photo before it joins the shared album.")),
                ('consent_note', models.TextField(blank=True, default='Selected photos may be used by the host for event highlights and social media. Please upload only appropriate event photos.')),
                ('max_photos_per_institution', models.PositiveIntegerField(default=36)),
                ('award_categories', models.JSONField(blank=True, default=apps.lens.models.default_award_categories)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_campaigns', to='organizations.organization')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_campaigns', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'lens_campaign',
            },
        ),
        migrations.CreateModel(
            name='LensPass',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_minted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='lens.lenscampaign')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_passes', to='teams.institution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_passes', to='organizations.organization')),
            ],
            options={
                'db_table': 'lens_pass',
            },
        ),
        migrations.CreateModel(
            name='LensPhoto',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('upload_ref', models.UUIDField(db_index=True, default=apps.accounts.models.uuid7, editable=False)),
                ('image', models.FileField(upload_to=apps.lens.models.photo_upload_to)),
                ('thumb', models.FileField(upload_to=apps.lens.models.thumb_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=200)),
                ('award_category', models.CharField(blank=True, max_length=100)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='lens.lenspass')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_photos_approved', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lens.lenscampaign')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_photos_hidden', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_photos', to='teams.institution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_photos', to='organizations.organization')),
            ],
            options={
                'db_table': 'lens_photo',
            },
        ),
        migrations.AddConstraint(
            model_name='lenscampaign',
            constraint=models.UniqueConstraint(fields=('tournament',), name='uniq_lens_campaign_per_tournament'),
        ),
        migrations.AddIndex(
            model_name='lensphoto',
            index=models.Index(fields=['campaign', 'institution'], name='lens_photo_camp_inst_idx'),
        ),
        migrations.AddIndex(
            model_name='lensphoto',
            index=models.Index(fields=['campaign', 'approved_at'], name='lens_photo_camp_appr_idx'),
        ),
    ]
