# Generated by Django 5.1.15 on 2026-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscampaign',
            name='category_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lensphoto',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
