# Generated by Django 5.1.15 on 2026-07-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0002_lenscampaign_category_limits_lensphoto_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lenscampaign',
            name='uniq_lens_campaign_per_tournament',
        ),
    ]
