# Generated by Django 5.1.15 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0003_remove_lenscampaign_uniq_lens_campaign_per_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscampaign',
            name='share_minted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lenscampaign',
            name='share_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lenspass',
            name='code_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='lenspass',
            name='code_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenspass',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
