# Generated by Django 5.1.15 on 2026-08-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0004_lenscampaign_share_minted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenscampaign',
            name='instructions',
            field=models.TextField(blank=True, default="Scan the event QR code, pick your school and enter the code the host gave you. Capture the event from your school's point of view and upload your best shots from your own phone. The host reviews every photo before it joins the shared album."),
        ),
    ]
