# Generated by Django 5.1.15 on 2026-08-24 03:41

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0005_alter_lenscampaign_instructions'),
        ('organizations', '0006_organization_school_profile'),
        ('teams', '0015_backfill_crests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscampaign',
            name='story_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lenscampaign',
            name='story_photos_per_entry',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='lensphoto',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LensStory',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=200)),
                ('award_category', models.CharField(blank=True, max_length=100)),
                ('event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='lens.lenspass')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_stories_approved', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='lens.lenscampaign')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_stories_hidden', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_stories', to='teams.institution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_stories', to='organizations.organization')),
            ],
            options={
                'db_table': 'lens_story',
            },
        ),
        migrations.AddField(
            model_name='lensphoto',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='lens.lensstory'),
        ),
        migrations.AddIndex(
            model_name='lensstory',
            index=models.Index(fields=['campaign', 'institution'], name='lens_story_camp_inst_idx'),
        ),
        migrations.AddConstraint(
            model_name='lensstory',
            constraint=models.UniqueConstraint(fields=('campaign', 'institution', 'category'), name='uniq_lens_story_per_school_category'),
        ),
    ]
