# Generated by Django 5.1.15 on 2026-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0006_lenscampaign_story_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscampaign',
            name='share_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
