# Generated by Django 5.1.15 on 2026-08-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0007_lenscampaign_share_token_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensstory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
