# Generated by Django 5.1.15 on 2026-08-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0008_lensstory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenscampaign',
            name='publish_on_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lensphoto',
            name='photographer',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
