# Generated by Django 5.1.15 on 2026-08-26 02:33

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0009_lenscampaign_publish_on_upload_and_more'),
        ('organizations', '0006_organization_school_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LensJudge',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('token_encrypted', models.TextField(blank=True, default='')),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='lens.lenscampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_judges', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LensScore',
            fields=[
                ('id', models.UUIDField(default=apps.accounts.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('marks', models.JSONField(blank=True, default=dict)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lens.lenscampaign')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lens.lensjudge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_scores', to='organizations.organization')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lens.lensphoto')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lens.lensstory')),
            ],
        ),
        migrations.AddIndex(
            model_name='lensjudge',
            index=models.Index(fields=['campaign', 'revoked_at'], name='lens_judge_live_idx'),
        ),
        migrations.AddConstraint(
            model_name='lensscore',
            constraint=models.UniqueConstraint(condition=models.Q(('photo__isnull', False)), fields=('judge', 'photo'), name='uniq_lens_score_judge_photo'),
        ),
        migrations.AddConstraint(
            model_name='lensscore',
            constraint=models.UniqueConstraint(condition=models.Q(('story__isnull', False)), fields=('judge', 'story'), name='uniq_lens_score_judge_story'),
        ),
    ]
