# Generated by Django 5.1.15 on 2026-05-02 21:29

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.accounts.models.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("individual", "Individual"),
                            ("racket", "Racket"),
                            ("combat", "Combat / Martial arts"),
                            ("athletics", "Athletics"),
                            ("aquatics", "Aquatics"),
                            ("gymnastics", "Gymnastics"),
                            ("strength", "Strength sports"),
                            ("shooting", "Shooting / Archery"),
                            ("mind", "Mind sports"),
                            ("indigenous", "Indigenous / Traditional"),
                            ("adventure", "Adventure / Outdoor"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("coming_soon", "Coming soon"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "indigenous_to",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_team_sport", models.BooleanField(default=False)),
                ("is_individual_sport", models.BooleanField(default=False)),
                (
                    "python_module_path",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                ("display_order", models.PositiveIntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sports_sport",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["status"], name="sport_status_idx"),
                    models.Index(fields=["category"], name="sport_category_idx"),
                ],
            },
        ),
    ]
