from __future__ import annotations

from django.urls import path

from apps.disputes.views import TournamentDisputeView
from apps.fixtures.views import (
    AdvancementRefireView,
    ControlRoomDayView,
    FixtureSnapshotDetailView,
    FixtureSnapshotRestoreView,
    FixtureEditView,
    GenerateFixturesView,
    PreviewAllFixturesView,
    PreviewFixturesView,
    PublishAllFixturesView,
    ScheduleFixturesView,
    ShiftFixturesDayView,
    SwapFixtureSlotsView,
    SwissNextRoundView,
    TournamentCourtDetailView,
    TournamentCourtsView,
    TournamentFixtureSnapshotsView,
    TournamentDrawConfigView,
    TournamentFixtureReadinessView,
    TournamentFixturesView,
    TournamentScheduleChangesView,
    TournamentVenueDetailView,
    TournamentVenuesView,
)
from apps.forms.views import (
    GenerateInstitutionFormView,
    GenerateTeamFormView,
    TournamentFormsView,
)
from apps.lens.views import (
    LensCampaignsView,
    LensCloseView,
    LensIssueCodesView,
    LensOpenView,
    LensOverviewView,
    LensPassRevokeView,
    LensPassRotateView,
    LensPhotoApproveView,
    LensPhotoAwardView,
    LensPhotoHideView,
    LensPhotoListView,
    LensReopenView,
    LensShareCardView,
    LensStoryApproveView,
    LensStoryAwardView,
    LensStoryHideView,
    LensStoryListView,
)
from apps.matches.views import (
    TournamentLeadersView,
    TournamentMatchListView,
    TournamentStandingsView,
    TournamentSuspensionsView,
    TournamentTiesView,
)
from apps.permissions.views import (
    TournamentGrantView,
    TournamentPermissionMatrixView,
)
from apps.streaming.views import (
    TournamentCourtBroadcastQrView,
    TournamentCourtStreamDetailView,
    TournamentCourtStreamsView,
    TournamentStreamLinkDetailView,
    TournamentStreamLinksView,
)
from apps.teams.views import (
    InstitutionDetailView,
    InstitutionEditLinkView,
    InstitutionListCreateView,
    RegistrationLinkCreateView,
    TeamAccessCodesView,
    TeamCalendarLinkView,
    TeamRegistrationDetailView,
    TeamSeedsView,
    TeamWithdrawView,
    TournamentTeamsListView,
)
from apps.teams.views_roster import (
    TournamentRosterDetailView,
    TournamentRosterView,
)
from apps.teams.views_tournament_houses import (
    TournamentHouseDetailView,
    TournamentHouseListView,
    TournamentHouseMemberView,
)
from apps.tournaments.views import (
    BulkAssignCrewView,
    ConstraintTypesView,
    TournamentAuditView,
    TournamentBulkInvitationView,
    TournamentCloneView,
    TournamentCompleteView,
    TournamentCopySetupView,
    TournamentDetailView,
    TournamentInvitationCreateView,
    TournamentInvitationResendView,
    TournamentListCreateView,
    TournamentMemberDetailView,
    TournamentMembersView,
    TournamentPresetsView,
    TournamentSettingsView,
    TournamentSportsMetaView,
    TournamentSportsView,
    TournamentStagePreviewView,
    TournamentStageView,
)

urlpatterns = [
    path("", TournamentListCreateView.as_view(), name="tournament-list-create"),
    path(
        "constraint-types/",
        ConstraintTypesView.as_view(),
        name="tournament-constraint-types",
    ),
    path(
        "<uuid:tournament_id>/",
        TournamentDetailView.as_view(),
        name="tournament-detail",
    ),
    path(
        "<uuid:tournament_id>/copy-setup/",
        TournamentCopySetupView.as_view(),
        name="tournament-copy-setup",
    ),
    path(
        "<uuid:tournament_id>/clone/",
        TournamentCloneView.as_view(),
        name="tournament-clone",
    ),
    path(
        "<uuid:tournament_id>/settings/",
        TournamentSettingsView.as_view(),
        name="tournament-settings",
    ),
    path(
        "<uuid:tournament_id>/sports/",
        TournamentSportsView.as_view(),
        name="tournament-sports",
    ),
    path(
        "<uuid:tournament_id>/sports-meta/",
        TournamentSportsMetaView.as_view(),
        name="tournament-sports-meta",
    ),
    path(
        "<uuid:tournament_id>/presets/",
        TournamentPresetsView.as_view(),
        name="tournament-presets",
    ),
    path(
        "<uuid:tournament_id>/ties/",
        TournamentTiesView.as_view(),
        name="tournament-ties",
    ),
    path(
        "<uuid:tournament_id>/invitations/",
        TournamentInvitationCreateView.as_view(),
        name="tournament-invitation-create",
    ),
    path(
        "<uuid:tournament_id>/invitations/bulk/",
        TournamentBulkInvitationView.as_view(),
        name="tournament-invitation-bulk",
    ),
    path(
        "<uuid:tournament_id>/invitations/<uuid:invitation_id>/resend/",
        TournamentInvitationResendView.as_view(),
        name="tournament-invitation-resend",
    ),
    path(
        "<uuid:tournament_id>/members/",
        TournamentMembersView.as_view(),
        name="tournament-members",
    ),
    path(
        "<uuid:tournament_id>/members/<uuid:membership_id>/",
        TournamentMemberDetailView.as_view(),
        name="tournament-member-detail",
    ),
    path(
        "<uuid:tournament_id>/audit/",
        TournamentAuditView.as_view(),
        name="tournament-audit",
    ),
    path(
        "<uuid:tournament_id>/registration-link/",
        RegistrationLinkCreateView.as_view(),
        name="tournament-registration-link",
    ),
    path(
        "<uuid:tournament_id>/teams/",
        TournamentTeamsListView.as_view(),
        name="tournament-teams",
    ),
    path(
        "<uuid:tournament_id>/teams/seeds/",
        TeamSeedsView.as_view(),
        name="tournament-team-seeds",
    ),
    path(
        "<uuid:tournament_id>/teams/<uuid:team_id>/withdraw/",
        TeamWithdrawView.as_view(),
        name="tournament-team-withdraw",
    ),
    path(
        "<uuid:tournament_id>/teams/<uuid:team_id>/calendar-link/",
        TeamCalendarLinkView.as_view(),
        name="tournament-team-calendar-link",
    ),
    path(
        "<uuid:tournament_id>/teams/<uuid:team_id>/registration/",
        TeamRegistrationDetailView.as_view(),
        name="tournament-team-registration-detail",
    ),
    path(
        "<uuid:tournament_id>/institutions/<uuid:institution_id>/edit-link/",
        InstitutionEditLinkView.as_view(),
        name="tournament-institution-edit-link",
    ),
    path(
        "<uuid:tournament_id>/team-codes/",
        TeamAccessCodesView.as_view(),
        name="tournament-team-codes",
    ),
    path(
        "<uuid:tournament_id>/forms/",
        TournamentFormsView.as_view(),
        name="tournament-forms",
    ),
    path(
        "<uuid:tournament_id>/forms/generate-team/",
        GenerateTeamFormView.as_view(),
        name="tournament-generate-team-form",
    ),
    path(
        "<uuid:tournament_id>/forms/generate-institution/",
        GenerateInstitutionFormView.as_view(),
        name="tournament-generate-institution-form",
    ),
    path(
        "<uuid:tournament_id>/matches/",
        TournamentMatchListView.as_view(),
        name="tournament-matches",
    ),
    path(
        "<uuid:tournament_id>/standings/",
        TournamentStandingsView.as_view(),
        name="tournament-standings",
    ),
    path(
        "<uuid:tournament_id>/suspensions/",
        TournamentSuspensionsView.as_view(),
        name="tournament-suspensions",
    ),
    path(
        "<uuid:tournament_id>/leaders/",
        TournamentLeadersView.as_view(),
        name="tournament-leaders",
    ),
    path(
        "<uuid:tournament_id>/generate-fixtures/",
        GenerateFixturesView.as_view(),
        name="tournament-generate-fixtures",
    ),
    path(
        "<uuid:tournament_id>/schedule/",
        ScheduleFixturesView.as_view(),
        name="tournament-schedule-fixtures",
    ),
    path(
        "<uuid:tournament_id>/draw-config/",
        TournamentDrawConfigView.as_view(),
        name="tournament-draw-config",
    ),
    # Every fixture this tournament has had, and a way back to one.
    path(
        "<uuid:tournament_id>/fixtures/edit/",
        FixtureEditView.as_view(),
        name="tournament-fixture-edit",
    ),
    path(
        "<uuid:tournament_id>/fixture-versions/",
        TournamentFixtureSnapshotsView.as_view(),
        name="tournament-fixture-versions",
    ),
    path(
        "<uuid:tournament_id>/fixture-readiness/",
        TournamentFixtureReadinessView.as_view(),
        name="tournament-fixture-readiness",
    ),
    path(
        "<uuid:tournament_id>/fixtures/",
        TournamentFixturesView.as_view(),
        name="tournament-fixtures",
    ),
    path(
        "<uuid:tournament_id>/fixtures/preview/",
        PreviewFixturesView.as_view(),
        name="tournament-fixtures-preview",
    ),
    path(
        "<uuid:tournament_id>/fixtures/preview-all/",
        PreviewAllFixturesView.as_view(),
        name="tournament-fixtures-preview-all",
    ),
    path(
        "<uuid:tournament_id>/fixtures/publish-all/",
        PublishAllFixturesView.as_view(),
        name="tournament-fixtures-publish-all",
    ),
    path(
        "<uuid:tournament_id>/fixtures/next-round/",
        SwissNextRoundView.as_view(),
        name="tournament-fixtures-next-round",
    ),
    path(
        "<uuid:tournament_id>/fixtures/swap-slots/",
        SwapFixtureSlotsView.as_view(),
        name="tournament-fixtures-swap-slots",
    ),
    path(
        "<uuid:tournament_id>/fixtures/shift-day/",
        ShiftFixturesDayView.as_view(),
        name="tournament-fixtures-shift-day",
    ),
    path(
        "<uuid:tournament_id>/schedule-changes/",
        TournamentScheduleChangesView.as_view(),
        name="tournament-schedule-changes",
    ),
    path(
        "<uuid:tournament_id>/control-room/",
        ControlRoomDayView.as_view(),
        name="tournament-control-room",
    ),
    path(
        "<uuid:tournament_id>/crew/bulk-assign/",
        BulkAssignCrewView.as_view(),
        name="tournament-crew-bulk-assign",
    ),
    path(
        "<uuid:tournament_id>/advancement:refire/",
        AdvancementRefireView.as_view(),
        name="tournament-advancement-refire",
    ),
    path(
        "<uuid:tournament_id>/permissions/",
        TournamentPermissionMatrixView.as_view(),
        name="tournament-permission-matrix",
    ),
    path(
        "<uuid:tournament_id>/permissions/grants/",
        TournamentGrantView.as_view(),
        name="tournament-permission-grants",
    ),
    path(
        "<uuid:tournament_id>/venues/",
        TournamentVenuesView.as_view(),
        name="tournament-venues",
    ),
    path(
        "<uuid:tournament_id>/venues/<uuid:venue_id>/",
        TournamentVenueDetailView.as_view(),
        name="tournament-venue-detail",
    ),
    path(
        "<uuid:tournament_id>/courts/",
        TournamentCourtsView.as_view(),
        name="tournament-courts",
    ),
    path(
        "<uuid:tournament_id>/courts/<uuid:court_id>/",
        TournamentCourtDetailView.as_view(),
        name="tournament-court-detail",
    ),
    # Per-court streaming bindings (spec 2026-08-03). Phase 1 is a pasted
    # YouTube watch URL per court; the public "Watch live" link stays OURS.
    path(
        "<uuid:tournament_id>/court-streams/",
        TournamentCourtStreamsView.as_view(),
        name="tournament-court-streams",
    ),
    path(
        "<uuid:tournament_id>/court-streams/<uuid:court_id>/",
        TournamentCourtStreamDetailView.as_view(),
        name="tournament-court-stream-detail",
    ),
    # The QR code of a court's phone broadcast page. A copy button can only
    # ever move that URL around the laptop it is displayed on; the phone that
    # films the match reads it off the screen with its camera.
    path(
        "<uuid:tournament_id>/court-streams/<uuid:court_id>/broadcast-qr/",
        TournamentCourtBroadcastQrView.as_view(),
        name="tournament-court-broadcast-qr",
    ),
    # Hand-pasted watch links at whichever scope the organiser works at — one
    # match, one court for one day, one competition category. Most specific
    # wins; the full precedence rule lives in apps.streaming.services.links.
    path(
        "<uuid:tournament_id>/stream-links/",
        TournamentStreamLinksView.as_view(),
        name="tournament-stream-links",
    ),
    path(
        "<uuid:tournament_id>/stream-links/<uuid:link_id>/",
        TournamentStreamLinkDetailView.as_view(),
        name="tournament-stream-link-detail",
    ),
    path(
        "<uuid:tournament_id>/institutions/",
        InstitutionListCreateView.as_view(),
        name="tournament-institutions",
    ),
    path(
        "<uuid:tournament_id>/institutions/<uuid:institution_id>/",
        InstitutionDetailView.as_view(),
        name="tournament-institution-detail",
    ),
    path(
        "<uuid:tournament_id>/houses/",
        TournamentHouseListView.as_view(),
        name="tournament-houses",
    ),
    path(
        "<uuid:tournament_id>/houses/<uuid:house_id>/",
        TournamentHouseDetailView.as_view(),
        name="tournament-house-detail",
    ),
    path(
        "<uuid:tournament_id>/houses/<uuid:house_id>/members/",
        TournamentHouseMemberView.as_view(),
        name="tournament-house-members",
    ),
    # Participants (spec 2026-08-17): the people a school declares before any
    # team exists, and every competition each of them ended up in.
    path(
        "<uuid:tournament_id>/roster/",
        TournamentRosterView.as_view(),
        name="tournament-roster",
    ),
    path(
        "<uuid:tournament_id>/roster/<uuid:member_id>/",
        TournamentRosterDetailView.as_view(),
        name="tournament-roster-detail",
    ),
    path(
        "<uuid:tournament_id>/disputes/",
        TournamentDisputeView.as_view(),
        name="tournament-disputes",
    ),
    path(
        "<uuid:tournament_id>/stage/",
        TournamentStageView.as_view(),
        name="tournament-stage",
    ),
    path(
        "<uuid:tournament_id>/stage/preview/",
        TournamentStagePreviewView.as_view(),
        name="tournament-stage-preview",
    ),
    path(
        "<uuid:tournament_id>/complete/",
        TournamentCompleteView.as_view(),
        name="tournament-complete",
    ),
    path(
        "<uuid:tournament_id>/lens/",
        LensOverviewView.as_view(),
        name="tournament-lens",
    ),
    path(
        "<uuid:tournament_id>/lens/campaigns/",
        LensCampaignsView.as_view(),
        name="tournament-lens-campaigns",
    ),
    path(
        "<uuid:tournament_id>/lens/open/",
        LensOpenView.as_view(),
        name="tournament-lens-open",
    ),
    path(
        "<uuid:tournament_id>/lens/close/",
        LensCloseView.as_view(),
        name="tournament-lens-close",
    ),
    path(
        "<uuid:tournament_id>/lens/reopen/",
        LensReopenView.as_view(),
        name="tournament-lens-reopen",
    ),
    path(
        "<uuid:tournament_id>/lens/share-card/",
        LensShareCardView.as_view(),
        name="tournament-lens-share-card",
    ),
    path(
        "<uuid:tournament_id>/lens/passes/codes/",
        LensIssueCodesView.as_view(),
        name="tournament-lens-passes-codes",
    ),
    path(
        "<uuid:tournament_id>/lens/passes/<uuid:pass_id>/rotate/",
        LensPassRotateView.as_view(),
        name="tournament-lens-pass-rotate",
    ),
    path(
        "<uuid:tournament_id>/lens/passes/<uuid:pass_id>/revoke/",
        LensPassRevokeView.as_view(),
        name="tournament-lens-pass-revoke",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/",
        LensPhotoListView.as_view(),
        name="tournament-lens-photos",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/<uuid:photo_id>/approve/",
        LensPhotoApproveView.as_view(),
        name="tournament-lens-photo-approve",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/<uuid:photo_id>/hide/",
        LensPhotoHideView.as_view(),
        name="tournament-lens-photo-hide",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/<uuid:photo_id>/award/",
        LensPhotoAwardView.as_view(),
        name="tournament-lens-photo-award",
    ),
    path(
        "<uuid:tournament_id>/lens/stories/",
        LensStoryListView.as_view(),
        name="tournament-lens-stories",
    ),
    path(
        "<uuid:tournament_id>/lens/stories/<uuid:story_id>/approve/",
        LensStoryApproveView.as_view(),
        name="tournament-lens-story-approve",
    ),
    path(
        "<uuid:tournament_id>/lens/stories/<uuid:story_id>/hide/",
        LensStoryHideView.as_view(),
        name="tournament-lens-story-hide",
    ),
    path(
        "<uuid:tournament_id>/lens/stories/<uuid:story_id>/award/",
        LensStoryAwardView.as_view(),
        name="tournament-lens-story-award",
    ),
]
