from __future__ import annotations

from django.urls import path

from apps.disputes.views import TournamentDisputeView
from apps.fixtures.views import (
    GenerateFixturesView,
    PreviewFixturesView,
    ScheduleFixturesView,
    TournamentDrawConfigView,
    TournamentFixtureReadinessView,
    TournamentFixturesView,
    TournamentVenueDetailView,
    TournamentVenuesView,
)
from apps.permissions.views import (
    TournamentGrantView,
    TournamentPermissionMatrixView,
)
from apps.forms.views import (
    GenerateInstitutionFormView,
    GenerateTeamFormView,
    TournamentFormsView,
)
from apps.matches.views import TournamentMatchListView, TournamentStandingsView
from apps.teams.views import (
    InstitutionDetailView,
    InstitutionListCreateView,
    InstitutionEditLinkView,
    RegistrationLinkCreateView,
    TeamAccessCodesView,
    TeamSeedsView,
    TournamentTeamsListView,
)
from apps.tournaments.views import (
    ConstraintTypesView,
    TournamentAuditView,
    TournamentDetailView,
    TournamentInvitationCreateView,
    TournamentListCreateView,
    TournamentMemberDetailView,
    TournamentMembersView,
    TournamentSettingsView,
    TournamentSportsView,
    TournamentStagePreviewView,
    TournamentStageView,
)

urlpatterns = [
    path("", TournamentListCreateView.as_view(), name="tournament-list-create"),
    path(
        "constraint-types/",
        ConstraintTypesView.as_view(),
        name="tournament-constraint-types",
    ),
    path(
        "<uuid:tournament_id>/",
        TournamentDetailView.as_view(),
        name="tournament-detail",
    ),
    path(
        "<uuid:tournament_id>/settings/",
        TournamentSettingsView.as_view(),
        name="tournament-settings",
    ),
    path(
        "<uuid:tournament_id>/sports/",
        TournamentSportsView.as_view(),
        name="tournament-sports",
    ),
    path(
        "<uuid:tournament_id>/invitations/",
        TournamentInvitationCreateView.as_view(),
        name="tournament-invitation-create",
    ),
    path(
        "<uuid:tournament_id>/members/",
        TournamentMembersView.as_view(),
        name="tournament-members",
    ),
    path(
        "<uuid:tournament_id>/members/<uuid:membership_id>/",
        TournamentMemberDetailView.as_view(),
        name="tournament-member-detail",
    ),
    path(
        "<uuid:tournament_id>/audit/",
        TournamentAuditView.as_view(),
        name="tournament-audit",
    ),
    path(
        "<uuid:tournament_id>/registration-link/",
        RegistrationLinkCreateView.as_view(),
        name="tournament-registration-link",
    ),
    path(
        "<uuid:tournament_id>/teams/",
        TournamentTeamsListView.as_view(),
        name="tournament-teams",
    ),
    path(
        "<uuid:tournament_id>/teams/seeds/",
        TeamSeedsView.as_view(),
        name="tournament-team-seeds",
    ),
    path(
        "<uuid:tournament_id>/institutions/<uuid:institution_id>/edit-link/",
        InstitutionEditLinkView.as_view(),
        name="tournament-institution-edit-link",
    ),
    path(
        "<uuid:tournament_id>/team-codes/",
        TeamAccessCodesView.as_view(),
        name="tournament-team-codes",
    ),
    path(
        "<uuid:tournament_id>/forms/",
        TournamentFormsView.as_view(),
        name="tournament-forms",
    ),
    path(
        "<uuid:tournament_id>/forms/generate-team/",
        GenerateTeamFormView.as_view(),
        name="tournament-generate-team-form",
    ),
    path(
        "<uuid:tournament_id>/forms/generate-institution/",
        GenerateInstitutionFormView.as_view(),
        name="tournament-generate-institution-form",
    ),
    path(
        "<uuid:tournament_id>/matches/",
        TournamentMatchListView.as_view(),
        name="tournament-matches",
    ),
    path(
        "<uuid:tournament_id>/standings/",
        TournamentStandingsView.as_view(),
        name="tournament-standings",
    ),
    path(
        "<uuid:tournament_id>/generate-fixtures/",
        GenerateFixturesView.as_view(),
        name="tournament-generate-fixtures",
    ),
    path(
        "<uuid:tournament_id>/schedule/",
        ScheduleFixturesView.as_view(),
        name="tournament-schedule-fixtures",
    ),
    path(
        "<uuid:tournament_id>/draw-config/",
        TournamentDrawConfigView.as_view(),
        name="tournament-draw-config",
    ),
    path(
        "<uuid:tournament_id>/fixture-readiness/",
        TournamentFixtureReadinessView.as_view(),
        name="tournament-fixture-readiness",
    ),
    path(
        "<uuid:tournament_id>/fixtures/",
        TournamentFixturesView.as_view(),
        name="tournament-fixtures",
    ),
    path(
        "<uuid:tournament_id>/fixtures/preview/",
        PreviewFixturesView.as_view(),
        name="tournament-fixtures-preview",
    ),
    path(
        "<uuid:tournament_id>/permissions/",
        TournamentPermissionMatrixView.as_view(),
        name="tournament-permission-matrix",
    ),
    path(
        "<uuid:tournament_id>/permissions/grants/",
        TournamentGrantView.as_view(),
        name="tournament-permission-grants",
    ),
    path(
        "<uuid:tournament_id>/venues/",
        TournamentVenuesView.as_view(),
        name="tournament-venues",
    ),
    path(
        "<uuid:tournament_id>/venues/<uuid:venue_id>/",
        TournamentVenueDetailView.as_view(),
        name="tournament-venue-detail",
    ),
    path(
        "<uuid:tournament_id>/institutions/",
        InstitutionListCreateView.as_view(),
        name="tournament-institutions",
    ),
    path(
        "<uuid:tournament_id>/institutions/<uuid:institution_id>/",
        InstitutionDetailView.as_view(),
        name="tournament-institution-detail",
    ),
    path(
        "<uuid:tournament_id>/disputes/",
        TournamentDisputeView.as_view(),
        name="tournament-disputes",
    ),
    path(
        "<uuid:tournament_id>/stage/",
        TournamentStageView.as_view(),
        name="tournament-stage",
    ),
    path(
        "<uuid:tournament_id>/stage/preview/",
        TournamentStagePreviewView.as_view(),
        name="tournament-stage-preview",
    ),
]
