from __future__ import annotations

from django.urls import path

from apps.disputes.views import TournamentDisputeView
from apps.matches.views import TournamentTiesView
from apps.fixtures.views import (
    AdvancementRefireView,
    ControlRoomDayView,
    GenerateFixturesView,
    PreviewAllFixturesView,
    PreviewFixturesView,
    PublishAllFixturesView,
    ScheduleFixturesView,
    ShiftFixturesDayView,
    SwapFixtureSlotsView,
    SwissNextRoundView,
    TournamentDrawConfigView,
    TournamentFixtureReadinessView,
    TournamentFixturesView,
    TournamentScheduleChangesView,
    TournamentVenueDetailView,
    TournamentVenuesView,
)
from apps.lens.views import (
    LensCloseView,
    LensMintPassesView,
    LensOpenView,
    LensOverviewView,
    LensPassRevokeView,
    LensPassRotateView,
    LensPhotoApproveView,
    LensPhotoAwardView,
    LensPhotoHideView,
    LensPhotoListView,
    LensReopenView,
)
from apps.forms.views import (
    GenerateInstitutionFormView,
    GenerateTeamFormView,
    TournamentFormsView,
)
from apps.matches.views import (
    TournamentLeadersView,
    TournamentMatchListView,
    TournamentStandingsView,
    TournamentSuspensionsView,
)
from apps.permissions.views import (
    TournamentGrantView,
    TournamentPermissionMatrixView,
)
from apps.teams.views import (
    InstitutionDetailView,
    InstitutionEditLinkView,
    InstitutionListCreateView,
    RegistrationLinkCreateView,
    TeamAccessCodesView,
    TeamCalendarLinkView,
    TeamRegistrationDetailView,
    TeamSeedsView,
    TeamWithdrawView,
    TournamentTeamsListView,
)
from apps.tournaments.views import (
    BulkAssignCrewView,
    ConstraintTypesView,
    TournamentAuditView,
    TournamentCompleteView,
    TournamentDetailView,
    TournamentInvitationCreateView,
    TournamentListCreateView,
    TournamentMemberDetailView,
    TournamentMembersView,
    TournamentPresetsView,
    TournamentSettingsView,
    TournamentSportsMetaView,
    TournamentSportsView,
    TournamentStagePreviewView,
    TournamentStageView,
)

urlpatterns = [
    path("", TournamentListCreateView.as_view(), name="tournament-list-create"),
    path(
        "constraint-types/",
        ConstraintTypesView.as_view(),
        name="tournament-constraint-types",
    ),
    path(
        "<uuid:tournament_id>/",
        TournamentDetailView.as_view(),
        name="tournament-detail",
    ),
    path(
        "<uuid:tournament_id>/settings/",
        TournamentSettingsView.as_view(),
        name="tournament-settings",
    ),
    path(
        "<uuid:tournament_id>/sports/",
        TournamentSportsView.as_view(),
        name="tournament-sports",
    ),
    path(
        "<uuid:tournament_id>/sports-meta/",
        TournamentSportsMetaView.as_view(),
        name="tournament-sports-meta",
    ),
    path(
        "<uuid:tournament_id>/presets/",
        TournamentPresetsView.as_view(),
        name="tournament-presets",
    ),
    path(
        "<uuid:tournament_id>/ties/",
        TournamentTiesView.as_view(),
        name="tournament-ties",
    ),
    path(
        "<uuid:tournament_id>/invitations/",
        TournamentInvitationCreateView.as_view(),
        name="tournament-invitation-create",
    ),
    path(
        "<uuid:tournament_id>/members/",
        TournamentMembersView.as_view(),
        name="tournament-members",
    ),
    path(
        "<uuid:tournament_id>/members/<uuid:membership_id>/",
        TournamentMemberDetailView.as_view(),
        name="tournament-member-detail",
    ),
    path(
        "<uuid:tournament_id>/audit/",
        TournamentAuditView.as_view(),
        name="tournament-audit",
    ),
    path(
        "<uuid:tournament_id>/registration-link/",
        RegistrationLinkCreateView.as_view(),
        name="tournament-registration-link",
    ),
    path(
        "<uuid:tournament_id>/teams/",
        TournamentTeamsListView.as_view(),
        name="tournament-teams",
    ),
    path(
        "<uuid:tournament_id>/teams/seeds/",
        TeamSeedsView.as_view(),
        name="tournament-team-seeds",
    ),
    path(
        "<uuid:tournament_id>/teams/<uuid:team_id>/withdraw/",
        TeamWithdrawView.as_view(),
        name="tournament-team-withdraw",
    ),
    path(
        "<uuid:tournament_id>/teams/<uuid:team_id>/calendar-link/",
        TeamCalendarLinkView.as_view(),
        name="tournament-team-calendar-link",
    ),
    path(
        "<uuid:tournament_id>/teams/<uuid:team_id>/registration/",
        TeamRegistrationDetailView.as_view(),
        name="tournament-team-registration-detail",
    ),
    path(
        "<uuid:tournament_id>/institutions/<uuid:institution_id>/edit-link/",
        InstitutionEditLinkView.as_view(),
        name="tournament-institution-edit-link",
    ),
    path(
        "<uuid:tournament_id>/team-codes/",
        TeamAccessCodesView.as_view(),
        name="tournament-team-codes",
    ),
    path(
        "<uuid:tournament_id>/forms/",
        TournamentFormsView.as_view(),
        name="tournament-forms",
    ),
    path(
        "<uuid:tournament_id>/forms/generate-team/",
        GenerateTeamFormView.as_view(),
        name="tournament-generate-team-form",
    ),
    path(
        "<uuid:tournament_id>/forms/generate-institution/",
        GenerateInstitutionFormView.as_view(),
        name="tournament-generate-institution-form",
    ),
    path(
        "<uuid:tournament_id>/matches/",
        TournamentMatchListView.as_view(),
        name="tournament-matches",
    ),
    path(
        "<uuid:tournament_id>/standings/",
        TournamentStandingsView.as_view(),
        name="tournament-standings",
    ),
    path(
        "<uuid:tournament_id>/suspensions/",
        TournamentSuspensionsView.as_view(),
        name="tournament-suspensions",
    ),
    path(
        "<uuid:tournament_id>/leaders/",
        TournamentLeadersView.as_view(),
        name="tournament-leaders",
    ),
    path(
        "<uuid:tournament_id>/generate-fixtures/",
        GenerateFixturesView.as_view(),
        name="tournament-generate-fixtures",
    ),
    path(
        "<uuid:tournament_id>/schedule/",
        ScheduleFixturesView.as_view(),
        name="tournament-schedule-fixtures",
    ),
    path(
        "<uuid:tournament_id>/draw-config/",
        TournamentDrawConfigView.as_view(),
        name="tournament-draw-config",
    ),
    path(
        "<uuid:tournament_id>/fixture-readiness/",
        TournamentFixtureReadinessView.as_view(),
        name="tournament-fixture-readiness",
    ),
    path(
        "<uuid:tournament_id>/fixtures/",
        TournamentFixturesView.as_view(),
        name="tournament-fixtures",
    ),
    path(
        "<uuid:tournament_id>/fixtures/preview/",
        PreviewFixturesView.as_view(),
        name="tournament-fixtures-preview",
    ),
    path(
        "<uuid:tournament_id>/fixtures/preview-all/",
        PreviewAllFixturesView.as_view(),
        name="tournament-fixtures-preview-all",
    ),
    path(
        "<uuid:tournament_id>/fixtures/publish-all/",
        PublishAllFixturesView.as_view(),
        name="tournament-fixtures-publish-all",
    ),
    path(
        "<uuid:tournament_id>/fixtures/next-round/",
        SwissNextRoundView.as_view(),
        name="tournament-fixtures-next-round",
    ),
    path(
        "<uuid:tournament_id>/fixtures/swap-slots/",
        SwapFixtureSlotsView.as_view(),
        name="tournament-fixtures-swap-slots",
    ),
    path(
        "<uuid:tournament_id>/fixtures/shift-day/",
        ShiftFixturesDayView.as_view(),
        name="tournament-fixtures-shift-day",
    ),
    path(
        "<uuid:tournament_id>/schedule-changes/",
        TournamentScheduleChangesView.as_view(),
        name="tournament-schedule-changes",
    ),
    path(
        "<uuid:tournament_id>/control-room/",
        ControlRoomDayView.as_view(),
        name="tournament-control-room",
    ),
    path(
        "<uuid:tournament_id>/crew/bulk-assign/",
        BulkAssignCrewView.as_view(),
        name="tournament-crew-bulk-assign",
    ),
    path(
        "<uuid:tournament_id>/advancement:refire/",
        AdvancementRefireView.as_view(),
        name="tournament-advancement-refire",
    ),
    path(
        "<uuid:tournament_id>/permissions/",
        TournamentPermissionMatrixView.as_view(),
        name="tournament-permission-matrix",
    ),
    path(
        "<uuid:tournament_id>/permissions/grants/",
        TournamentGrantView.as_view(),
        name="tournament-permission-grants",
    ),
    path(
        "<uuid:tournament_id>/venues/",
        TournamentVenuesView.as_view(),
        name="tournament-venues",
    ),
    path(
        "<uuid:tournament_id>/venues/<uuid:venue_id>/",
        TournamentVenueDetailView.as_view(),
        name="tournament-venue-detail",
    ),
    path(
        "<uuid:tournament_id>/institutions/",
        InstitutionListCreateView.as_view(),
        name="tournament-institutions",
    ),
    path(
        "<uuid:tournament_id>/institutions/<uuid:institution_id>/",
        InstitutionDetailView.as_view(),
        name="tournament-institution-detail",
    ),
    path(
        "<uuid:tournament_id>/disputes/",
        TournamentDisputeView.as_view(),
        name="tournament-disputes",
    ),
    path(
        "<uuid:tournament_id>/stage/",
        TournamentStageView.as_view(),
        name="tournament-stage",
    ),
    path(
        "<uuid:tournament_id>/stage/preview/",
        TournamentStagePreviewView.as_view(),
        name="tournament-stage-preview",
    ),
    path(
        "<uuid:tournament_id>/complete/",
        TournamentCompleteView.as_view(),
        name="tournament-complete",
    ),
    path(
        "<uuid:tournament_id>/lens/",
        LensOverviewView.as_view(),
        name="tournament-lens",
    ),
    path(
        "<uuid:tournament_id>/lens/open/",
        LensOpenView.as_view(),
        name="tournament-lens-open",
    ),
    path(
        "<uuid:tournament_id>/lens/close/",
        LensCloseView.as_view(),
        name="tournament-lens-close",
    ),
    path(
        "<uuid:tournament_id>/lens/reopen/",
        LensReopenView.as_view(),
        name="tournament-lens-reopen",
    ),
    path(
        "<uuid:tournament_id>/lens/passes/mint/",
        LensMintPassesView.as_view(),
        name="tournament-lens-passes-mint",
    ),
    path(
        "<uuid:tournament_id>/lens/passes/<uuid:pass_id>/rotate/",
        LensPassRotateView.as_view(),
        name="tournament-lens-pass-rotate",
    ),
    path(
        "<uuid:tournament_id>/lens/passes/<uuid:pass_id>/revoke/",
        LensPassRevokeView.as_view(),
        name="tournament-lens-pass-revoke",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/",
        LensPhotoListView.as_view(),
        name="tournament-lens-photos",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/<uuid:photo_id>/approve/",
        LensPhotoApproveView.as_view(),
        name="tournament-lens-photo-approve",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/<uuid:photo_id>/hide/",
        LensPhotoHideView.as_view(),
        name="tournament-lens-photo-hide",
    ),
    path(
        "<uuid:tournament_id>/lens/photos/<uuid:photo_id>/award/",
        LensPhotoAwardView.as_view(),
        name="tournament-lens-photo-award",
    ),
]
