# Generated by Django 5.1.15 on 2026-06-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationmembership",
            name="single_org_per_admin_user",
        ),
    ]
