# Generated by Django 5.1.15 on 2026-06-05 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0002_remove_organizationmembership_single_org_per_admin_user",
        ),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="admininvitation",
            name="unique_pending_invite_per_email_per_org",
        ),
        migrations.AddField(
            model_name="admininvitation",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="admininvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("organization", "tournament", "email"),
                name="unique_pending_invite_per_email_per_org_tournament",
            ),
        ),
    ]
