# Generated by Django 5.1.15 on 2026-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0003_remove_admininvitation_unique_pending_invite_per_email_per_org_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
