# Generated by Django 5.1.15 on 2026-07-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_admininvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='branding',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal workspace'), ('institution', 'Institution')], db_index=True, default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
