# Generated by Django 5.1.15 on 2026-07-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_branding_organization_is_listed_and_more'),
        ('teams', '0010_schoolprofile_institution_school_profile_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='school_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_orgs', to='teams.schoolprofile'),
        ),
    ]
